package com.cpgame.wukong.server;

import com.cpgame.wukong.core.GameRuleCore;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.*;
import com.sun.net.httpserver.*;
import java.io.*;
import java.math.*;
import java.net.*;
import java.nio.charset.StandardCharsets;
import java.nio.file.*;
import java.security.SecureRandom;
import java.time.Instant;
import java.util.*;
import java.util.concurrent.*;
import java.util.concurrent.atomic.AtomicLong;

/** Controller contract v3：一个受管 Java PID、一个动态 5xxxx 端口、仅 Redis 完整局。 */
public final class WuKongController {
    private static final ObjectMapper JSON=new ObjectMapper();private static final SecureRandom RANDOM=new SecureRandom();private static final AtomicLong OID=new AtomicLong(System.currentTimeMillis()*1000L);private static final Map<String,Session> SESSIONS=new ConcurrentHashMap<>();
    private final Path publish;private final BigDecimal initialBalance;private final RedisRoundStore store;private final WuKongProjector projector=new WuKongProjector();
    private WuKongController(Path publish,BigDecimal balance,RedisRoundStore store){this.publish=publish.toAbsolutePath().normalize();this.initialBalance=balance;this.store=store;}
    public static void main(String[] args)throws Exception{Map<String,String> opt=options(args);int port=requiredPort(opt);String configPath=opt.get("config");Properties p=load(configPath);validateConfigKeys(p);if(!"0.0.0.0".equals(p.getProperty("server.bind","0.0.0.0").trim()))throw new IllegalArgumentException("server.bind must be 0.0.0.0");Path root=resolvePublish(opt.getOrDefault("publish",p.getProperty("demo.publish-directory","")),configPath);RedisRoundStore store=RedisRoundStore.connect(p);WuKongController c=new WuKongController(root,new BigDecimal(p.getProperty("session.initial-balance","100000.00")),store);HttpServer server=HttpServer.create(new InetSocketAddress("0.0.0.0",port),0);server.createContext("/",c::handle);server.setExecutor(Executors.newFixedThreadPool(Math.max(4,Runtime.getRuntime().availableProcessors())));Runtime.getRuntime().addShutdownHook(new Thread(()->{server.stop(0);try{store.close();}catch(IOException ignored){}}));server.start();System.out.printf("CONTROLLER_READY gameId=2210 port=%d pid=%d rulesHash=%s publish=%s redis=18.234.101.161:8021/db15%n",port,ProcessHandle.current().pid(),GameRuleCore.RULES_HASH,root);}
    private void handle(HttpExchange x)throws IOException{try{if("OPTIONS".equalsIgnoreCase(x.getRequestMethod())){send(x,204,new byte[0],"text/plain");return;}String path=x.getRequestURI().getPath();if("GET".equalsIgnoreCase(x.getRequestMethod())||"HEAD".equalsIgnoreCase(x.getRequestMethod())){if(path.equals("/favicon.ico")){send(x,204,new byte[0],"image/x-icon");return;}if(path.equals("/health")||path.equals("/api/capabilities")){json(x,capabilities());return;}if(path.equals("/api/balance")){json(x,okWith("data",balance(session(x,query(x.getRequestURI().getRawQuery())))));return;}if(path.equals("/api/session")){json(x,okWith("data",sessionJson(session(x,query(x.getRequestURI().getRawQuery())))));return;}staticFile(x);return;}if(!"POST".equalsIgnoreCase(x.getRequestMethod())){error(x,405,"method not allowed");return;}Map<String,String> form=form(x);Session s=session(x,form);switch(path){case"/cp/config/initialData"->json(x,initialData(form));case"/cp/account/getUserInfo"->json(x,userInfo(s));case"/cp/activity/getActivity"->json(x,activity());case"/cp/single_game.black_myth_wukong/initRoom"->json(x,init(s));case"/cp/single_game.black_myth_wukong/gameResult"->json(x,spin(x,s,form));case"/cp/single_game.black_myth_wukong/getUserHistory"->json(x,recent(s));case"/cp/goldGame/wukong_user_gold_history","/cp/goldgame/wukong_user_gold_history"->json(x,summary(s,form));case"/cp/goldGame/wukong_user_history","/cp/goldgame/wukong_user_history"->json(x,detail(s,form));case"/api/balance"->json(x,okWith("data",balance(s)));case"/api/session"->json(x,okWith("data",sessionJson(s)));default->error(x,404,"unknown endpoint");}}catch(IllegalArgumentException e){error(x,400,e.getMessage());}catch(IllegalStateException e){error(x,503,e.getMessage());}catch(Exception e){e.printStackTrace(System.err);error(x,500,"controller failure");}finally{x.close();}}
    private ObjectNode spin(HttpExchange x,Session s,Map<String,String> form)throws Exception{synchronized(s){String key=first(x.getRequestHeaders().getFirst("Idempotency-Key"),form.get("idempotency_key"),form.get("request_id"));if(key!=null&&s.idempotent.containsKey(key))return s.idempotent.get(key).deepCopy();BigDecimal bet=decimal(form.getOrDefault("bet_gold","1"));if(bet.signum()<=0)throw new IllegalArgumentException("bet_gold must be positive");if(s.balance.compareTo(bet)<0)throw new IllegalArgumentException("insufficient balance");RedisRoundStore.Claimed claimed=store.claim(RANDOM);ObjectNode data=projector.project(claimed.round(),bet,s.balance,OID.incrementAndGet());s.balance=data.path("end_gold").decimalValue().setScale(2,RoundingMode.HALF_UP);s.last=data.deepCopy();ObjectNode row=historyRow(data);s.history.add(0,row);if(s.history.size()>200)s.history.subList(200,s.history.size()).clear();ObjectNode response=okWith("data",data);if(key!=null)s.idempotent.put(key,response.deepCopy());return response;}}
    private ObjectNode historyRow(ObjectNode spin){ObjectNode item=spin.deepCopy();long day=Instant.now().getEpochSecond()/86400*86400;item.put("day",day);item.put("time",Instant.now().getEpochSecond());item.put("order_id",item.path("oid").asText()+"-2210");item.set("result",item.path("chess").deepCopy());ObjectNode extend=item.putObject("extend");extend.put("act_bet_gold",0).put("act_id","0").put("act_type",0);ObjectNode delivery=item.deepCopy();delivery.put("bet",false);delivery.set("result",delivery.path("chess").deepCopy());delivery.remove("results");item.putArray("results").add(delivery);return item;}
    private ObjectNode init(Session s){synchronized(s){return okWith("data",s.last==null?projector.idle(s.balance):s.last.deepCopy());}}
    private ObjectNode recent(Session s){synchronized(s){ArrayNode list=JSON.createArrayNode();s.history.stream().limit(30).forEach(item->{ObjectNode row=list.addObject();row.put("begin_time",item.path("begin_time").asText());row.set("bets_gold",item.path("bet_gold").deepCopy());row.set("bet_gold",item.path("bet_gold").deepCopy());row.set("win_gold",item.path("win_gold").deepCopy());row.set("profit_gold",item.path("profit_gold").deepCopy());row.set("chess",item.path("chess").deepCopy());});return okWith("data",list);}}
    private ObjectNode summary(Session s,Map<String,String> form){synchronized(s){Map<Long,BigDecimal[]> days=new TreeMap<>(Comparator.reverseOrder());BigDecimal totalBet=BigDecimal.ZERO,totalChange=BigDecimal.ZERO;for(ObjectNode item:s.history){long day=item.path("day").asLong();BigDecimal bet=item.path("bet_gold").decimalValue(),change=item.path("change_gold").decimalValue();BigDecimal[] row=days.computeIfAbsent(day,k->new BigDecimal[]{BigDecimal.ZERO,BigDecimal.ZERO});row[0]=row[0].add(bet);row[1]=row[1].add(change);totalBet=totalBet.add(bet);totalChange=totalChange.add(change);}ObjectNode data=JSON.createObjectNode();ArrayNode list=data.putArray("list");for(var e:page(new ArrayList<>(days.entrySet()),form)){ObjectNode row=list.addObject().put("day",e.getKey());number(row,"bet_gold",e.getValue()[0]);number(row,"change_gold",e.getValue()[1]);}ObjectNode stat=data.putObject("statistics");number(stat,"total_bet_gold",totalBet);number(stat,"total_change_gold",totalChange);return okWith("data",data);}}
    private ObjectNode detail(Session s,Map<String,String> form){synchronized(s){List<ObjectNode> rows=s.history;if(form.containsKey("day")){long day=Long.parseLong(form.get("day"));rows=s.history.stream().filter(v->v.path("day").asLong()==day).toList();}BigDecimal totalBet=rows.stream().map(v->v.path("bet_gold").decimalValue()).reduce(BigDecimal.ZERO,BigDecimal::add),totalChange=rows.stream().map(v->v.path("change_gold").decimalValue()).reduce(BigDecimal.ZERO,BigDecimal::add);ObjectNode data=JSON.createObjectNode();ArrayNode list=data.putArray("list");page(rows,form).forEach(v->list.add(v.deepCopy()));ObjectNode stat=data.putObject("statistics");number(stat,"total_bet_gold",totalBet);number(stat,"total_change_gold",totalChange);return okWith("data",data);}}
    private static <T> List<T> page(List<T> rows,Map<String,String> f){int p=positive(f.getOrDefault("page","1")),size=positive(f.getOrDefault("page_size","30")),from=Math.min(rows.size(),(p-1)*size),to=Math.min(rows.size(),from+size);return rows.subList(from,to);}
    private ObjectNode initialData(Map<String,String> f){String language=f.getOrDefault("language",f.getOrDefault("l","pt-br"));if(!GameRuleCore.LANGUAGES.contains(language))language="pt-br";ObjectNode d=JSON.createObjectNode();d.putObject("game_address").putObject("ship_address_config");d.put("language",language).put("zone",0).put("r",1);d.putObject("initial_config").put("is_stopgs",0).put("is_debug",false).put("current_sys_time",Instant.now().getEpochSecond()).put("bd_bet_count",2).put("user_on_hook_time",600).put("version",1745909504);ObjectNode g=d.putObject("game_info");g.put("gid",2210).put("name","Magic Scroll").put("status","1").put("default_bet_gold",0).put("default_level",1).put("least_gold",0).put("buy_free_max_bet",-1);g.set("bet_gold",JSON.valueToTree(List.of(1,5,10,50,100)));g.putArray("game_way").addObject().put("way_id",221010000).put("min_bet_gold","0.00").put("max_bet_gold","0.00").put("win_multi","1.00");ObjectNode gs=d.putObject("game_server");for(String k:List.of("gos_host","gos_sport","gs_host","gs_host1","gs_port","gs_port1","gs_push_host","gs_push_port","gs_sport","gs_sport1","ps_host","ps_port","snake_gs_host","snake_gs_port","snake_gs_sport","snake_gs_url"))gs.put(k,"");gs.put("ngs_switch",0).put("gos_port","8976").put("gs_push_sport","28966");return okWith("data",d);}
    private ObjectNode userInfo(Session s){ObjectNode d=JSON.createObjectNode().put("token",s.key).put("uid",2210001).put("gid",2210).put("nickname","Wu Kong Demo").put("currency_symbol","R$").put("day_first_login",0).putNull("first_gold").put("is_guide",0).put("total_recharge","0");d.putArray("user_config");number(d,"gold",s.balance);return okWith("data",d);}private ObjectNode activity(){ObjectNode d=JSON.createObjectNode();ObjectNode free=d.putObject("free");free.putArray("act_list");free.put("invite_act_have",0).put("invite_end_time",0);return okWith("data",d);}
    private ObjectNode capabilities(){ObjectNode n=JSON.createObjectNode().put("status","UP").put("gameId",2210).put("rulesVersion",GameRuleCore.RULES_VERSION).put("rulesHash",GameRuleCore.RULES_HASH).put("controllerContractVersion",3).put("demoReadsRedisCache",true).put("selectsWinOrLossThenMultiplier",true).put("completeRoundsPreloaded",true).put("ordinaryLossUsesRuntimeGenerator",false).put("runtimeDealWhenCacheEmpty",false).put("completeRoundDeliveryCount",1);n.set("languages",JSON.valueToTree(GameRuleCore.LANGUAGES));n.set("specialModes",JSON.valueToTree(List.of("SPECIAL_X2","SPECIAL_X5","SPECIAL_RESPIN")));return n;}
    private ObjectNode balance(Session s){ObjectNode n=JSON.createObjectNode();number(n,"balance",s.balance);return n;}private ObjectNode sessionJson(Session s){synchronized(s){ObjectNode n=balance(s).put("session",s.key).put("historyCount",s.history.size()).put("rulesHash",GameRuleCore.RULES_HASH).put("gid",2210);return n;}}
    private Session session(HttpExchange x,Map<String,String> values){String key=first(values.get("token"),values.get("t"),query(x.getRequestURI().getRawQuery()).get("token"),"local-replay");return SESSIONS.computeIfAbsent(key,k->new Session(k,initialBalance));}
    private void staticFile(HttpExchange x)throws IOException{URI uri=x.getRequestURI();if("/".equals(uri.getPath())&&!query(uri.getRawQuery()).containsKey("sip")){String host=x.getRequestHeaders().getFirst("Host");if(host==null)host="127.0.0.1";Map<String,String> q=query(uri.getRawQuery());q.putIfAbsent("gid","2210");q.putIfAbsent("language",q.getOrDefault("l","pt-br"));q.putIfAbsent("token",q.getOrDefault("t","local-replay"));q.put("sip",host);StringJoiner join=new StringJoiner("&");q.forEach((k,v)->join.add(enc(k)+"="+enc(v)));x.getResponseHeaders().set("Location","/?"+join);send(x,302,new byte[0],"text/plain");return;}String raw=uri.getPath();if(raw.isBlank()||raw.equals("/"))raw="/index.html";Path file=publish.resolve(raw.substring(1)).normalize();if(!file.startsWith(publish)||!Files.isRegularFile(file)){error(x,404,"static file not found");return;}byte[] body=Files.readAllBytes(file);send(x,200,"HEAD".equalsIgnoreCase(x.getRequestMethod())?new byte[0]:body,mime(file),body.length);}
    private static Map<String,String> form(HttpExchange x)throws IOException{return query(new String(x.getRequestBody().readAllBytes(),StandardCharsets.UTF_8));}private static Map<String,String> query(String raw){Map<String,String> map=new LinkedHashMap<>();if(raw==null||raw.isBlank())return map;for(String part:raw.split("&")){String[] p=part.split("=",2);map.put(dec(p[0]),p.length==2?dec(p[1]):"");}return map;}private static String dec(String s){return URLDecoder.decode(s,StandardCharsets.UTF_8);}private static String enc(String s){return URLEncoder.encode(s,StandardCharsets.UTF_8);}
    private static Map<String,String> options(String[] args){Map<String,String> map=new HashMap<>();for(int i=0;i<args.length;i++){if(!args[i].startsWith("--")||i+1>=args.length)throw new IllegalArgumentException("arguments require --name value");map.put(args[i].substring(2),args[++i]);}return map;}private static int requiredPort(Map<String,String> o){if(!o.containsKey("port"))throw new IllegalArgumentException("--port is required");int p=Integer.parseInt(o.get("port"));if(p<50000||p>59999)throw new IllegalArgumentException("port must be 50000-59999");return p;}private static Properties load(String value)throws IOException{Properties p=new Properties();if(value!=null)try(InputStream in=Files.newInputStream(Path.of(value))){p.load(in);}return p;}private static Path resolvePublish(String raw,String configPath){if(raw==null||raw.isBlank())throw new IllegalArgumentException("--publish or demo.publish-directory required");Path value=Path.of(raw);Path p=value.isAbsolute()?value:(configPath==null?value.toAbsolutePath():Path.of(configPath).toAbsolutePath().getParent().resolve(value));p=p.normalize();if(!Files.isRegularFile(p.resolve("index.html")))throw new IllegalArgumentException("publish index.html missing: "+p);return p;}private static void validateConfigKeys(Properties p){Set<String> allowed=Set.of("controller.contract-version","controller.jar","controller.main-class","controller.config","controller.config-argument","controller.process-mode","controller.port-argument","controller.port-range","controller.publish-argument","demo.mode","demo.publish-directory","demo.entry-file","server.bind","session.initial-balance","redis.host","redis.port","redis.username","redis.password","redis.database","redis.ssl","redis.connect-timeout-ms","redis.socket-timeout-ms","redis.game-id");for(String key:p.stringPropertyNames())if(!allowed.contains(key))throw new IllegalArgumentException("unsupported formal configuration property "+key);}
    private static ObjectNode ok(){return JSON.createObjectNode().put("code",0).put("msg","success").put("time",Long.toString(Instant.now().getEpochSecond()));}private static ObjectNode okWith(String field,JsonNode value){ObjectNode n=ok();n.set(field,value);return n;}private static void json(HttpExchange x,JsonNode n)throws IOException{send(x,200,JSON.writeValueAsBytes(n),"application/json; charset=utf-8");}private static void error(HttpExchange x,int status,String message)throws IOException{ObjectNode n=JSON.createObjectNode().put("code",status).put("msg",message==null?"error":message);send(x,status,JSON.writeValueAsBytes(n),"application/json; charset=utf-8");}private static void send(HttpExchange x,int status,byte[] body,String type)throws IOException{send(x,status,body,type,body.length);}private static void send(HttpExchange x,int status,byte[] body,String type,long contentLength)throws IOException{x.getResponseHeaders().set("Content-Type",type);x.getResponseHeaders().set("Access-Control-Allow-Origin","*");x.getResponseHeaders().set("Access-Control-Allow-Headers","Content-Type, Idempotency-Key");x.getResponseHeaders().set("Access-Control-Allow-Methods","GET,POST,HEAD,OPTIONS");if("HEAD".equalsIgnoreCase(x.getRequestMethod())){x.sendResponseHeaders(status,contentLength);return;}x.sendResponseHeaders(status,body.length);x.getResponseBody().write(body);}private static String mime(Path p){String n=p.getFileName().toString().toLowerCase(Locale.ROOT);if(n.endsWith(".html"))return"text/html; charset=utf-8";if(n.endsWith(".js"))return"application/javascript";if(n.endsWith(".json"))return"application/json";if(n.endsWith(".css"))return"text/css";if(n.endsWith(".png"))return"image/png";if(n.endsWith(".jpg")||n.endsWith(".jpeg"))return"image/jpeg";if(n.endsWith(".mp3"))return"audio/mpeg";return"application/octet-stream";}
    private static int positive(String s){int n=Integer.parseInt(s);if(n<1)throw new IllegalArgumentException("positive integer required");return n;}private static BigDecimal decimal(String s){return new BigDecimal(s).setScale(2,RoundingMode.HALF_UP);}private static String first(String...values){for(String v:values)if(v!=null&&!v.isBlank())return v;return null;}private static void number(ObjectNode n,String f,BigDecimal v){v=v.stripTrailingZeros();if(v.scale()<=0)n.put(f,v.longValueExact());else n.put(f,v.doubleValue());}
    private static final class Session{final String key;BigDecimal balance;ObjectNode last;final List<ObjectNode> history=new ArrayList<>();final Map<String,ObjectNode> idempotent=new LinkedHashMap<>();Session(String key,BigDecimal balance){this.key=key;this.balance=balance;}}
}
