package com.cpgame.g2110.server;
import com.cpgame.g2110.core.*;import java.util.*;
final class ProtocolProjection{
 private final GameRuleCore rules=new GameRuleCore();private final ResultUtil util=new ResultUtil(rules);
 Map<String,Object>project(SessionState session,int index,double bet,int level){var round=session.active.round();var step=round.steps().get(index);boolean first=index==0,terminal=index==round.steps().size()-1,free=index>0;double wager=util.totalBet(bet,level),pageWin=util.moneyFromUnits(rules.payoutUnits(step.board()),bet,level),start=session.balance;if(first)session.balance=util.money(session.balance-wager);session.balance=util.money(session.balance+pageWin);if(free)session.cumulativeFreeWin=util.money(session.cumulativeFreeWin+pageWin);int totalFree=round.kind()==GameRuleCore.RoundKind.FREE_STICKY_SYMBOLS?round.steps().size()-1:0,remaining=free?totalFree-index:totalFree;
  Map<String,Object>data=new LinkedHashMap<>();data.put("bet",bet);data.put("bet_gold",wager);data.put("change_gold",util.money(pageWin-(first?wager:0)));data.put("end_gold",session.balance);data.put("frees",frees(step,bet,level,totalFree,remaining,session.cumulativeFreeWin));data.put("level",level);data.put("odds",wager==0?0:util.money(pageWin/wager));data.put("oid",String.valueOf(session.roundId));if(free)data.put("forder_id",String.valueOf(session.roundId));data.put("props",props(step,bet,level));data.put("small_game_type",free?2:0);data.put("spe_pos",step.specialPositions());data.put("start_gold",start);data.put("total_win",pageWin);data.put("type",free?2:1);return data;}
 private Map<String,Object>frees(GameRuleCore.Step step,double bet,int level,int total,int remaining,double cumulative){Map<String,Object>f=new LinkedHashMap<>();f.put("ba",total>0?util.totalBet(bet,level):0);f.put("bet",total>0?bet:0);f.put("fw",0);f.put("l",total>0?level:0);if(total>0)f.put("spe_pos",step.specialPositions());f.put("st",remaining);f.put("tt",total);f.put("twa",cumulative);return f;}
 private Map<String,Object>props(GameRuleCore.Step step,double bet,int level){List<Map<String,Object>>wins=new ArrayList<>();for(var w:rules.evaluate(step.board())){Map<String,Object>x=new LinkedHashMap<>();x.put("line",w.line());x.put("num",w.num());x.put("odd",w.odd());x.put("tw",util.moneyFromUnits(w.odd(),bet,level));x.put("wp",w.wp());wins.add(x);}Map<String,Object>p=new LinkedHashMap<>();p.put("frees_prop",rules.scatterCount(step.board()));p.put("prop",Arrays.stream(step.board()).boxed().toList());p.put("tw",util.moneyFromUnits(rules.payoutUnits(step.board()),bet,level));p.put("win_arr",wins);return p;}
}
