package com.cpgame.curupira;
import com.cpgame.curupira.codec.MinimalFactCodec;import com.cpgame.curupira.config.EngineConfiguration;import com.cpgame.curupira.core.*;import com.cpgame.curupira.redis.RedisContractGate;
import org.junit.jupiter.api.Test;import java.io.*;import java.nio.charset.StandardCharsets;import java.nio.file.*;import java.util.Properties;import static org.junit.jupiter.api.Assertions.*;
class SafetyAndProtocolTest{
 private static final Path FORMAL=Path.of("packaging/generator.properties");
 @Test void formalConfigurationIsSafeAndComplete()throws Exception{EngineConfiguration c=EngineConfiguration.load(FORMAL);assertEquals(Integer.MAX_VALUE,EngineConfiguration.MAX_GENERATION_TARGET);assertEquals(300,c.maxMembersPerMultiplier());assertEquals(100000,c.validationSamples());assertEquals(10,c.generationPolicy().symbolWeights().size());String text=Files.readString(FORMAL).toLowerCase();assertFalse(text.contains("seed"));assertFalse(text.contains(".probability"));assertFalse(text.contains(".evidence"));}
 @Test void unauthorizedModesFailButPlatformRedisAndCodecWork()throws Exception{Properties mode=props();mode.setProperty("modes.HOLD_AND_SPINS.enabled","false");assertThrows(IllegalArgumentException.class,()->EngineConfiguration.from(mode));assertTrue(new RedisContractGate().writable());assertEquals("BetLog:000002350:000001",new RedisContractGate().resultKey("ORDINARY_PAID",1,2350));assertEquals("MaryLog:000002350:000010",new RedisContractGate().resultKey("SPECIAL",10,2350));assertThrows(IllegalArgumentException.class,()->new MinimalFactCodec().encodeFact(null));}
 @Test void acceptedHandoffHasSameHashAndAllBehaviors()throws Exception{Path root=Path.of("../../protocol/2350-Curupira");String c=Files.readString(root.resolve("game-capabilities.json"),StandardCharsets.UTF_8),h=Files.readString(root.resolve("protocol-handoff.json"),StandardCharsets.UTF_8);assertTrue(c.contains(RulesContract.RULES_HASH));assertTrue(h.contains(RulesContract.RULES_HASH));for(String id:RulesContract.BEHAVIOR_IDS)assertTrue(h.contains(id),id);}
 @Test void productionHasNoRuntimeOracleDependency()throws Exception{try(var paths=Files.walk(Path.of("src/main"))){for(Path f:paths.filter(Files::isRegularFile).toList()){String s=Files.readString(f).toLowerCase();assertFalse(s.contains("fixture"),f.toString());assertFalse(s.contains("spin-index"),f.toString());assertFalse(s.contains("paid-rounds"),f.toString());assertFalse(s.contains("demo-script"),f.toString());}}}
 @Test void formalConfigurationUsesOnlyCurrentGameSymbolWeights()throws Exception{Properties p=props();p.setProperty("symbols.total-weight","10");assertThrows(IllegalArgumentException.class,()->EngineConfiguration.from(p));assertEquals(GameRules.SYMBOLS,EngineConfiguration.load(FORMAL).generationPolicy().symbolWeights().keySet());}
 private static Properties props()throws Exception{Properties p=new Properties();try(Reader r=Files.newBufferedReader(FORMAL,StandardCharsets.UTF_8)){p.load(r);}return p;}
}
