package com.cpgame.sharpshooter.server;

import com.cpgame.sharpshooter.core.*;import com.fasterxml.jackson.databind.ObjectMapper;import com.sun.net.httpserver.*;import java.io.*;import java.net.*;import java.nio.charset.StandardCharsets;import java.nio.file.*;import java.time.*;import java.util.*;import java.util.concurrent.*;

public final class SharpshooterController {
 private final ObjectMapper json=new ObjectMapper();private final ConcurrentMap<String,SessionState> sessions=new ConcurrentHashMap<>();private final SharpshooterProjector projector=new SharpshooterProjector();private RedisRoundStore redis;private Path publish;
 public static void main(String[] args)throws Exception{new SharpshooterController().start(load(args));}
 private void start(Properties p)throws Exception{if(!"3".equals(p.getProperty("controller.contract-version")))throw new IllegalArgumentException("contract v3 required");int port=Integer.parseInt(required(p,"server.port"));if(port<50000||port>59999)throw new IllegalArgumentException("port must be 50000-59999");publish=Path.of(required(p,"publish.directory")).toAbsolutePath().normalize();redis=new RedisRoundStore(p);HttpServer server=HttpServer.create(new InetSocketAddress(p.getProperty("server.bind","0.0.0.0"),port),0);server.createContext("/",this::handle);server.setExecutor(Executors.newFixedThreadPool(12));Runtime.getRuntime().addShutdownHook(new Thread(()->{server.stop(0);redis.close();}));server.start();System.out.printf("Sharpshooter contract-v3 listening=%d rulesHash=%s publish=%s%n",port,GameRuleCore.RULES_HASH,publish);}
 private void handle(HttpExchange x)throws IOException{try{cors(x);if("OPTIONS".equals(x.getRequestMethod())){x.sendResponseHeaders(204,-1);return;}String path=x.getRequestURI().getPath();if(path.equals("/healthz")){send(x,200,Map.of("status","UP","gameId",1090,"rulesHash",GameRuleCore.RULES_HASH));return;}if(path.equals("/api/report/timing")){send(x,200,ok(Map.of()));return;}if(path.startsWith("/cp/")){api(x,path.substring(3));return;}staticFile(x,path);}catch(RedisRoundStore.CacheEmptyException e){send(x,503,Map.of("code",50301,"msg","PREGENERATED_CACHE_EMPTY","detail",e.getMessage()));}catch(Exception e){send(x,500,Map.of("code",50000,"msg",e.getClass().getSimpleName()+":"+e.getMessage()));}finally{x.close();}}
 private void api(HttpExchange x,String path)throws IOException{Map<String,String> q=form(x);String token=q.getOrDefault("token","demo"),language=normalizeLanguage(q.getOrDefault("language","en"));SessionState s=sessions.computeIfAbsent(token,k->new SessionState());switch(path){
  case "/config/initialData"->send(x,200,ok(config(language)));
  case "/account/getUserInfo"->send(x,200,ok(user(token,s)));
  case "/activity/getActivity"->send(x,200,ok(Map.of("free",Map.of("act_list",List.of(),"invite_act_have",0,"invite_end_time",0))));
  case "/config/setGameConfig"->send(x,200,ok(Map.of()));
  case "/single_game.Shooter/initRoom"->send(x,200,ok(initRoom(s)));
  case "/single_game.Shooter/gameResult"->spin(x,s,q);
  case "/goldgame/shooter_user_gold_history"->send(x,200,ok(historySummary(s)));
  case "/goldgame/shooter_user_history"->send(x,200,ok(historyDetail(s)));
  default->send(x,404,Map.of("code",404,"msg","UNKNOWN_API","path",path));}}
 private void spin(HttpExchange x,SessionState s,Map<String,String> q)throws IOException{synchronized(s){double bet=s.activeRound==null?Double.parseDouble(q.getOrDefault("bet_gold","0.02")):s.betSize;int level=s.activeRound==null?Integer.parseInt(q.getOrDefault("level","10")):s.betLevel;if(s.activeRound==null){if(!Double.isFinite(bet)||bet<=0||level<=0)throw new IllegalArgumentException("invalid bet");RedisRoundStore.Selection select=selection(q.getOrDefault("outcome","any"));Integer multiplier=q.containsKey("multiplier")?Integer.valueOf(q.get("multiplier")):null;RedisRoundStore.Claim claim=redis.claim(select,multiplier);s.activeRound=claim.round();s.activeMember=claim.member();s.spinIndex=0;s.roundId=System.currentTimeMillis()*100;s.betSize=bet;s.betLevel=level;s.paidBet=SharpshooterProjector.money(bet*level*20);s.cumulativeFreeWin=0;s.activeResults.clear();}CompleteRound active=s.activeRound;Map<String,Object> data=projector.project(s,active,s.spinIndex,bet,level);s.lastResult=deepCopy(data);s.activeResults.add(deepCopy(data));boolean terminal=s.spinIndex==active.spins().size()-1;if(terminal){Map<String,Object> history=historyRecord(s,data);s.history.addFirst(history);while(s.history.size()>30)s.history.removeLast();s.activeRound=null;s.activeMember=null;s.spinIndex=0;s.activeResults.clear();}else s.spinIndex++;send(x,200,ok(data));}}
 private Map<String,Object> historyRecord(SessionState s,Map<String,Object> last){Map<String,Object> first=s.activeResults.get(0),h=new LinkedHashMap<>(first);List<Map<String,Object>> results=new ArrayList<>();for(Map<String,Object> state:s.activeResults){Map<String,Object> item=new LinkedHashMap<>(state);item.put("result",item.remove("props"));item.put("time",Instant.now().getEpochSecond());results.add(item);}h.put("day",LocalDate.now(ZoneOffset.UTC).atStartOfDay().toEpochSecond(ZoneOffset.UTC));h.put("order_id",s.roundId+"-1090");h.put("result",first.get("props"));h.put("results",results);h.put("time",Instant.now().getEpochSecond());h.put("change_gold",SharpshooterProjector.money(((Number)last.get("end_gold")).doubleValue()-((Number)first.get("start_gold")).doubleValue()));return h;}
 private Map<String,Object> historySummary(SessionState s){double bet=0,change=0;for(Map<String,Object> h:s.history){bet+=((Number)h.get("bet_gold")).doubleValue();change+=((Number)h.get("change_gold")).doubleValue();}long day=LocalDate.now(ZoneOffset.UTC).atStartOfDay().toEpochSecond(ZoneOffset.UTC);return Map.of("list",List.of(Map.of("bet_gold",SharpshooterProjector.money(bet),"change_gold",SharpshooterProjector.money(change),"day",day)),"statistics",Map.of("total_bet_gold",SharpshooterProjector.money(bet),"total_change_gold",SharpshooterProjector.money(change)));}
 private Map<String,Object> historyDetail(SessionState s){double bet=0,change=0;for(Map<String,Object> h:s.history){bet+=((Number)h.get("bet_gold")).doubleValue();change+=((Number)h.get("change_gold")).doubleValue();}return Map.of("list",new ArrayList<>(s.history),"page",1,"page_size",30,"statistics",Map.of("total_bet_gold",SharpshooterProjector.money(bet),"total_change_gold",SharpshooterProjector.money(change)));}
 private Map<String,Object> user(String token,SessionState s){return Map.ofEntries(Map.entry("currency_symbol","$"),Map.entry("day_first_login",0),Map.entry("gid",1090),Map.entry("gold",s.balance),Map.entry("is_guide",0),Map.entry("nickname","demo1090"),Map.entry("token",token),Map.entry("total_recharge","0"),Map.entry("uid",10900001),Map.entry("user_config",Map.of("game_config",Map.of("open_sound",1,"open_music",1,"open_auto_spin",1,"open_free_buy",1,"open_paytable",0,"act",List.of()))));}
 private Map<String,Object> config(String language){Map<String,Object> info=new LinkedHashMap<>();info.put("bet_gold",List.of(.02,.1,.5));info.put("buy_free_max_bet",-1);info.put("default_bet_gold",0);info.put("default_level",10);info.put("game_way",List.of(Map.of("max_bet_gold","0.00","min_bet_gold","0.00","way_id",109010000,"win_multi","1.00")));info.put("gid",1090);info.put("least_gold",0);info.put("name","Sharpshooter");info.put("status","1");return Map.of("game_address",Map.of("ship_address_config",Map.of()),"game_info",info,"game_server",Map.of(),"initial_config",Map.of("bd_bet_count",2,"current_sys_time",Instant.now().getEpochSecond(),"is_debug",false,"is_stopgs",0,"user_on_hook_time",600,"version",1745909504),"language",language,"r",1,"zone",0);}
 private Map<String,Object> initRoom(SessionState s){if(s.lastResult!=null){Map<String,Object> restored=deepCopy(s.lastResult);restored.put("prop_odds",paytable());restored.put("type_multiple",List.of(List.of(1,2,3,5),List.of(2,4,6,10)));return restored;}int[] board={1,2,3,4,5,6,7,8,2,3,4,5,6,7,8,1,3,4,5,9};boolean[] gold=new boolean[20];CompleteRound.Spin spin=new CompleteRound.Spin(true,0,0,0,List.of(new CompleteRound.Cascade(board,gold)));SessionState temp=new SessionState();temp.balance=s.balance;temp.paidBet=4;temp.roundId=0;Map<String,Object> data=projector.project(temp,new CompleteRound(List.of(spin)),0,.02,10);data.put("bet_gold",0);data.put("change_gold",0);data.put("end_gold",s.balance);data.put("start_gold",s.balance);data.put("oid",0);data.put("prop_odds",paytable());data.put("type_multiple",List.of(List.of(1,2,3,5),List.of(2,4,6,10)));return data;}
 private List<Map<String,Object>> paytable(){int[][] odds={{1,2,5,10},{2,2,5,10},{3,4,10,20},{4,4,10,20},{5,6,15,40},{6,8,20,60},{7,10,40,80},{8,15,60,100}};List<Map<String,Object>> out=new ArrayList<>();for(int[] x:odds)out.add(Map.of("prop_id",x[0],"odds",List.of(Map.of("num",3,"odds",x[1]),Map.of("num",4,"odds",x[2]),Map.of("num",5,"odds",x[3]))));return out;}
 private RedisRoundStore.Selection selection(String raw){return switch(raw.toLowerCase(Locale.ROOT)){case"loss"->RedisRoundStore.Selection.LOSS;case"win"->RedisRoundStore.Selection.WIN;case"special","free"->RedisRoundStore.Selection.SPECIAL;default->RedisRoundStore.Selection.ANY;};}
 private String normalizeLanguage(String s){s=s.toLowerCase(Locale.ROOT);return switch(s){case"en-us"->"en";case"es-es"->"es";default->s;};}
 private Map<String,Object> ok(Object data){return Map.of("code",0,"data",data,"msg","success","time",String.valueOf(Instant.now().getEpochSecond()));}
 @SuppressWarnings("unchecked") private Map<String,Object> deepCopy(Map<String,Object> m){return json.convertValue(m,Map.class);}
 private void staticFile(HttpExchange x,String raw)throws IOException{String path=raw;if(path.equals("/")){String host=x.getRequestHeaders().getFirst("Host");x.getResponseHeaders().set("Location","/v2/1090/index.html?gid=1090&language=en&token=demo&ai=demo&sip="+host);x.sendResponseHeaders(302,-1);return;}if(path.startsWith("/v2/1090/"))path=path.substring("/v2/1090".length());else if(path.startsWith("/v2/"))path=path.substring(3);Path f=publish.resolve(path.substring(1)).normalize();if(!f.startsWith(publish)||!Files.isRegularFile(f)){send(x,404,Map.of("code",404,"msg","STATIC_NOT_FOUND","path",raw));return;}byte[] body=Files.readAllBytes(f);x.getResponseHeaders().set("Content-Type",content(f));x.sendResponseHeaders(200,body.length);x.getResponseBody().write(body);}
 private String content(Path p){String s=p.toString().toLowerCase(Locale.ROOT);if(s.endsWith(".html"))return"text/html; charset=utf-8";if(s.endsWith(".js"))return"application/javascript; charset=utf-8";if(s.endsWith(".json"))return"application/json";if(s.endsWith(".png"))return"image/png";if(s.endsWith(".jpg"))return"image/jpeg";if(s.endsWith(".mp3"))return"audio/mpeg";if(s.endsWith(".ttf"))return"font/ttf";if(s.endsWith(".plist"))return"application/xml";return"application/octet-stream";}
 private Map<String,String> form(HttpExchange x)throws IOException{String raw=new String(x.getRequestBody().readAllBytes(),StandardCharsets.UTF_8);Map<String,String> out=new LinkedHashMap<>();for(String part:raw.split("&")){if(part.isBlank())continue;String[] kv=part.split("=",2);out.put(URLDecoder.decode(kv[0],StandardCharsets.UTF_8),URLDecoder.decode(kv.length>1?kv[1]:"",StandardCharsets.UTF_8));}return out;}
 private void send(HttpExchange x,int status,Object value)throws IOException{byte[] body=json.writeValueAsBytes(value);x.getResponseHeaders().set("Content-Type","application/json; charset=utf-8");x.sendResponseHeaders(status,body.length);x.getResponseBody().write(body);}
 private void cors(HttpExchange x){x.getResponseHeaders().set("Access-Control-Allow-Origin","*");x.getResponseHeaders().set("Access-Control-Allow-Headers","Content-Type, Authorization");x.getResponseHeaders().set("Access-Control-Allow-Methods","GET, POST, OPTIONS");}
 static Properties load(String[] args)throws IOException{
  Properties overrides=new Properties();Path config=Path.of("dist/controller.properties");boolean explicit=false;
  for(int i=0;i<args.length;i++){
   String arg=args[i];
   if(arg.equals("--config")||arg.equals("--port")||arg.equals("--server.port")||arg.equals("--publish")){
    if(++i>=args.length)throw new IllegalArgumentException("missing value for "+arg);
    if(arg.equals("--config")){config=Path.of(args[i]);explicit=true;}
    else overrides.setProperty(arg.equals("--publish")?"publish.directory":"server.port",args[i]);
   }else if(arg.startsWith("--config=")){config=Path.of(arg.substring(9));explicit=true;}
   else if(arg.startsWith("--publish="))overrides.setProperty("publish.directory",arg.substring(10));
   else if(arg.startsWith("--port=")||arg.startsWith("--server.port="))overrides.setProperty("server.port",arg.substring(arg.indexOf('=')+1));
   else if(!arg.startsWith("--")&&!explicit){config=Path.of(arg);explicit=true;}
   else throw new IllegalArgumentException("unsupported argument "+arg);
  }
  config=config.toAbsolutePath().normalize();Properties p=new Properties();
  try(Reader reader=Files.newBufferedReader(config,StandardCharsets.UTF_8)){p.load(reader);}
  if(!overrides.containsKey("publish.directory")){
   Path directory=Path.of(required(p,"publish.directory"));
   if(!directory.isAbsolute())directory=config.getParent().resolve(directory);
   p.setProperty("publish.directory",directory.toAbsolutePath().normalize().toString());
  }
  String env=System.getenv("PORT");if(env!=null&&!env.isBlank())p.setProperty("server.port",env);
  p.putAll(overrides);
  if(p.containsKey("publish.directory"))p.setProperty("publish.directory",Path.of(p.getProperty("publish.directory")).toAbsolutePath().normalize().toString());
  return p;
 }
 private static String required(Properties p,String k){String v=p.getProperty(k);if(v==null||v.isBlank())throw new IllegalArgumentException("missing "+k);return v;}
}
