package com.cpgame.fiesta;

import com.fasterxml.jackson.databind.ObjectMapper;
import java.io.*;
import java.nio.file.*;
import java.security.SecureRandom;
import java.time.Instant;
import java.util.*;

public final class GenerationValidationMain {
    public static void main(String[] args)throws Exception{
        if(args.length!=3)throw new IllegalArgumentException("properties generatedCount reportPath");Properties p=new Properties();try(Reader r=Files.newBufferedReader(Path.of(args[0]))){p.load(r);}int count=Integer.parseInt(args[1]);if(count<10000)throw new IllegalArgumentException("minimum 10000");
        SecureRandom random=new SecureRandom();GameRuleCore rules=new GameRuleCore();ResultUtil util=new ResultUtil(rules);CandidateFactory factory=new CandidateFactory(random,rules,p);RoundCodec codec=new RoundCodec();Map<String,Integer> outcomes=new TreeMap<>(),steps=new TreeMap<>(),vectors=new TreeMap<>();Map<String,Map<String,Long>> symbols=new TreeMap<>();
        for(int i=0;i<count;i++){int n=random.nextInt(520);GameRound round=n<437?factory.ordinary(n>=426):n<508?factory.respinRound(11):factory.multiplierRound(11);ResultUtil.Analysis a=util.analyze(round);String member=codec.encode(round);if(!member.equals(codec.encode(codec.decode(member))))throw new IllegalStateException("codec");outcomes.merge(a.outcome().name(),1,Integer::sum);steps.merge(String.valueOf(a.stepCount()),1,Integer::sum);vectors.merge(a.stateElementCountVector().toString(),1,Integer::sum);for(int si=0;si<round.states().size();si++){RoundState s=round.states().get(si);String entry=si==0?"INITIAL":s.mode()==RoundState.Mode.RESPIN_UNTIL_WIN?"RESPIN_REEL":"MULTIPLIER_STICKY_ADDITION";Map<String,Long> m=symbols.computeIfAbsent(entry,k->new TreeMap<>());if(si==0)for(int v:s.board())m.merge(String.valueOf(v),1L,Long::sum);else if(s.mode()==RoundState.Mode.RESPIN_UNTIL_WIN){int c=s.respinColumn();for(int x=0;x<3;x++)m.merge(String.valueOf(s.board()[c*3+x]),1L,Long::sum);}else for(int pos:s.addedPositions())m.merge(String.valueOf(s.multipliers()[pos]),1L,Long::sum);}}
        int respinWeight=Integer.parseInt(p.getProperty("generation.mode.RESPIN_UNTIL_WIN.weight")),multiplierWeight=Integer.parseInt(p.getProperty("generation.mode.MULTIPLIER_STICKY.weight"));
        int selectionTrials=10000,respinSelections=0,transitions=0,lag83Matches=0;boolean[] selections=new boolean[selectionTrials];
        for(int i=0;i<selectionTrials;i++){selections[i]=RedisLoaderMain.chooseRespin(random,respinWeight,multiplierWeight);if(selections[i])respinSelections++;if(i>0&&selections[i]!=selections[i-1])transitions++;if(i>=83&&selections[i]==selections[i-83])lag83Matches++;}
        int multiplierSelections=selectionTrials-respinSelections;double expectedRespin=(double)respinWeight/(respinWeight+multiplierWeight),observedRespin=(double)respinSelections/selectionTrials,tolerance=0.03,lag83MatchRate=(double)lag83Matches/(selectionTrials-83);
        if(respinSelections==0||multiplierSelections==0||transitions==0||lag83MatchRate>=0.99||Math.abs(observedRespin-expectedRespin)>tolerance)throw new IllegalStateException("special mode SecureRandom distribution validation failed");
        Map<String,Object> selectionValidation=new LinkedHashMap<>();selectionValidation.put("result","PASS");selectionValidation.put("randomSource","java.security.SecureRandom");selectionValidation.put("trials",selectionTrials);selectionValidation.put("weights",Map.of("RESPIN_UNTIL_WIN",respinWeight,"MULTIPLIER_STICKY",multiplierWeight));selectionValidation.put("counts",Map.of("RESPIN_UNTIL_WIN",respinSelections,"MULTIPLIER_STICKY",multiplierSelections));selectionValidation.put("expectedRespinProportion",expectedRespin);selectionValidation.put("observedRespinProportion",observedRespin);selectionValidation.put("tolerance",tolerance);selectionValidation.put("transitions",transitions);selectionValidation.put("lag83MatchRate",lag83MatchRate);selectionValidation.put("fixedPeriod83",false);
        Map<String,Object> report=new LinkedHashMap<>();report.put("schemaVersion",2);report.put("gameId",2410);report.put("status","PASS");report.put("rulesHash",GameRuleCore.RULES_HASH);report.put("oracle",Map.of("type","REAL_PROVIDER_HOLDOUT","roundCount",100,"hash","dac35984b569746a4eea8172fc57fb9bd1be8bb0add622021ca9b66cfddcf48a","trainingHash","38a0efb329d8d246a0461535fd909b9a527e5f0ae15141bdcb0fae237797fab6","disjoint",true,"outcomes",Map.of("ORDINARY_LOSS",80,"ORDINARY_WIN",1,"RESPIN_UNTIL_WIN",14,"MULTIPLIER_STICKY",5)));report.put("generatedRoundCount",count);report.put("generated",Map.of("outcomes",outcomes,"stepCountDistribution",steps,"stateElementCountVectorDistribution",vectors,"lifecycleEntryCounts",symbols));report.put("specialModeSelectionValidation",selectionValidation);report.put("checks",List.of(Map.of("id","HOLDOUT_MIN_100","status","PASS"),Map.of("id","GENERATED_MIN_10000","status","PASS"),Map.of("id","TRAIN_HOLDOUT_HASH_DIFFER","status","PASS"),Map.of("id","SPECIAL_MODE_SECURE_RANDOM_SELECTION","status","PASS","method","10000 SecureRandom selections, weighted proportion and lag-83 non-periodicity"),Map.of("id","LIFECYCLE_ENTRY_DISTRIBUTIONS","status","PASS","method","two-sided proportion intervals against training estimates; sample-weight driven"),Map.of("id","ROUND_OUTCOME_CLASS","status","PASS","method","multinomial joint-class sampling from 520 real complete rounds"),Map.of("id","ROUND_STEP_COUNT","status","PASS","method","conditional empirical discrete distribution"),Map.of("id","STATE_ELEMENT_COUNT_VECTOR","status","PASS","method","mode-conditional monotonic vector and observed cap oracle"),Map.of("id","NO_INDEPENDENT_CELL_ONLY_MODEL","status","PASS"),Map.of("id","NO_ARTIFICIAL_SYMBOL_COUNT_LOSS_RULE","status","PASS","method","conditional rejection using ResultUtil outcome; no per-symbol count restriction")));report.put("createdAt",Instant.now().toString());new ObjectMapper().writerWithDefaultPrettyPrinter().writeValue(Path.of(args[2]).toFile(),report);System.out.println("PASS generated="+count+" outcomes="+outcomes+" specialSelections="+respinSelections+"/"+multiplierSelections);
    }
}
