package com.cpgame.beachfun.api;
import com.cpgame.beachfun.core.*;import com.fasterxml.jackson.databind.*;import com.sun.net.httpserver.*;import java.io.*;import java.net.*;import java.nio.charset.StandardCharsets;import java.nio.file.*;import java.time.*;import java.util.*;import java.util.concurrent.*;

/** Contract-v3 static host and stateful API. Paid outcomes are claimed from configured Redis; the idle screen is an uncharged legal board. */
public final class ControllerMain{
 private static final java.util.concurrent.atomic.AtomicLong ROUND_IDS=new java.util.concurrent.atomic.AtomicLong(System.currentTimeMillis()*1000);
 private final ObjectMapper json=new ObjectMapper();private final ConcurrentMap<String,SessionState>sessions=new ConcurrentHashMap<>();private final ProtocolProjection projection=new ProtocolProjection();private RedisRoundRepository redis;private Path publish;private final GameRuleCore.Delivery idleBoard=createIdleBoard();
 public static void main(String[]args)throws Exception{new ControllerMain().start(load(args));}
 private void start(Properties p)throws Exception{if(!"3".equals(p.getProperty("controller.contract-version")))throw new IllegalArgumentException("contract v3 required");String portText=p.getProperty("server.port");if(portText==null||portText.isBlank())throw new IllegalArgumentException("server.port required via --port");int port=Integer.parseInt(portText);if(port<50000||port>59999)throw new IllegalArgumentException("port must be 50000..59999");publish=Path.of(p.getProperty("publish.directory")).toAbsolutePath().normalize();if(!Files.isRegularFile(publish.resolve("index.html")))throw new IllegalArgumentException("publish index missing");redis=new RedisRoundRepository(p);HttpServer server=HttpServer.create(new InetSocketAddress(p.getProperty("server.bind","0.0.0.0"),port),0);server.createContext("/",this::handle);server.setExecutor(Executors.newFixedThreadPool(12));Runtime.getRuntime().addShutdownHook(new Thread(()->{server.stop(0);redis.close();}));server.start();System.out.println("Beach Fun contract v3 listening port="+port+" rulesHash="+GameRuleCore.RULES_HASH);}
 private void handle(HttpExchange x)throws IOException{try{cors(x);if("OPTIONS".equals(x.getRequestMethod())){x.sendResponseHeaders(204,-1);return;}String path=x.getRequestURI().getPath();if(path.startsWith("/cp/")){cp(x,path.substring(3));return;}if(path.startsWith("/api/")){api(x,path.substring(5));return;}if(path.equals("/health")){send(x,200,Map.of("status","UP","gameId",1940,"contractVersion",3,"rulesHash",GameRuleCore.RULES_HASH,"runtimeSource","REDIS_DB15_PREGENERATED_ONLY"));return;}staticFile(x,path);}catch(IllegalArgumentException e){send(x,400,Map.of("code",40001,"msg","INVALID_REQUEST","detail",Objects.toString(e.getMessage(),"")));}catch(RedisRoundRepository.CacheEmptyException e){send(x,503,Map.of("code",50301,"msg","PREGENERATED_CACHE_EMPTY","detail",e.getMessage()));}catch(Exception e){send(x,500,Map.of("code",50000,"msg",e.getClass().getSimpleName()+":"+e.getMessage()));}finally{x.close();}}
 private void cp(HttpExchange x,String path)throws IOException{Map<String,String>q=form(x);SessionState s=session(q);switch(path){case "/api/v1/auth/verify"->send(x,200,Map.of("code",200,"info","ok","data",Map.of("player",Map.of("balance",String.valueOf(s.balance),"id",19400001),"token",q.getOrDefault("token","demo"),"ping",Map.of("enable",0,"seconds",0),"rc",Map.of("on",0,"v",2),"gc",Map.of("os",1,"om",1))));case "/config/initialData"->send(x,200,ok(config(q.getOrDefault("language","pt-br"))));case "/account/getUserInfo"->send(x,200,ok(Map.ofEntries(Map.entry("token",q.getOrDefault("token","demo")),Map.entry("gold",s.balance),Map.entry("currency_symbol","R$"),Map.entry("day_first_login",0),Map.entry("first_gold",0),Map.entry("gid",1940),Map.entry("is_guide",0),Map.entry("nickname","1940-demo"),Map.entry("total_recharge","0"),Map.entry("uid",19400001),Map.entry("user_config",Map.of("game_config",Map.of("ac",List.of(),"open_auto_spin",1,"open_free_buy",0,"open_music",1,"open_paytable",0,"open_sound",1))))));case "/activity/getActivity"->send(x,200,ok(Map.of("free",Map.of("act_list",List.of(),"invite_act_have",0,"invite_end_time",0))));case "/single_game.beath/initRoom","/single_game.Beath/initRoom"->send(x,200,ok(initRoom(s)));case "/single_game.Beath/gameResult","/single_game.beath/gameResult"->spin(x,s,q);case "/goldgame/single_game_user_gold_history","/goldgame/beath_user_gold_history"->send(x,200,ok(historyDays(s)));case "/goldgame/single_game_user_history","/goldgame/beath_user_history"->send(x,200,ok(history(s,q)));default->send(x,404,Map.of("code",404,"msg","UNKNOWN_API","path",path));}}
 private void api(HttpExchange x,String path)throws IOException{Map<String,String>q=form(x);SessionState s=session(q);switch(path){case "init"->send(x,200,initRoom(s));case "config"->send(x,200,config(q.getOrDefault("language","pt-br")));case "spin"->spin(x,s,q);case "history"->send(x,200,history(s,q));case "balance"->send(x,200,Map.of("balance",s.balance));case "session"->send(x,200,Map.of("session",q.getOrDefault("token","demo"),"activeRound",s.active!=null,"deliveryIndex",s.deliveryIndex));default->send(x,404,Map.of("code",404,"msg","UNKNOWN_API"));}}
 private void spin(HttpExchange x,SessionState s,Map<String,String>q)throws IOException {
  if(!"POST".equals(x.getRequestMethod())){send(x,405,Map.of("code",405,"msg","POST_REQUIRED"));return;}
  synchronized(s){
   double bet=number(q,"bet_gold",number(q,"bet",.02)),rawLevel=number(q,"level",10);
   if(!Double.isFinite(bet)||!(bet==.02||bet==.1||bet==.2)||rawLevel!=Math.rint(rawLevel)||rawLevel<1||rawLevel>10)throw new IllegalArgumentException("bet/level outside captured configuration");
   int level=(int)rawLevel;
   if(s.active==null){
    double charge=ResultUtil.totalBet(bet,level);if(s.balance<charge){send(x,409,Map.of("code",40901,"msg","INSUFFICIENT_BALANCE"));return;}
    var claimed=redis.claim();s.active=claimed;s.betGold=bet;s.level=level;s.roundStartBalance=s.balance;
    s.deliveryIndex=0;s.roundId=ROUND_IDS.getAndAdd(1000);s.freeWin=0;s.priorFreeWin=0;s.roundResponses.clear();
   }else if(bet!=s.betGold||level!=s.level){send(x,409,Map.of("code",40902,"msg","BET_LOCKED_UNTIL_ROUND_COMPLETE"));return;}
   var data=projection.project(s,s.active,s.deliveryIndex,s.betGold,s.level);
   s.lastData=new LinkedHashMap<>(data);s.roundResponses.add(new LinkedHashMap<>(data));
   boolean terminal=s.deliveryIndex==s.active.round().deliveries().size()-1;
   if(terminal){s.history.addFirst(historyEntry(s));while(s.history.size()>30)s.history.removeLast();s.active=null;s.deliveryIndex=0;}
   else s.deliveryIndex++;
   send(x,200,ok(data));
  }
 }
 private Map<String,Object>historyEntry(SessionState s){
  long day=LocalDate.now(ZoneOffset.UTC).atStartOfDay().toEpochSecond(ZoneOffset.UTC),now=Instant.now().getEpochSecond();
  List<Map<String,Object>>results=new ArrayList<>();
  for(var response:s.roundResponses){
   Map<String,Object>item=new LinkedHashMap<>(response);item.put("result",item.remove("props"));item.put("bet",false);
   item.put("day",day);item.put("time",now);item.put("extend",Map.of("act_bet_gold",0,"act_id",0,"act_type",0));results.add(item);
  }
  Map<String,Object>entry=new LinkedHashMap<>(s.roundResponses.get(0));entry.put("result",entry.remove("props"));
  entry.put("results",List.copyOf(results));entry.put("order_id",s.roundId+"-1940");entry.put("day",day);entry.put("time",now);
  entry.put("extend",Map.of("act_bet_gold",0,"act_id",0,"act_type",0));
  entry.put("start_gold",s.roundStartBalance);entry.put("end_gold",s.balance);
  double total=ResultUtil.moneyFromUnits(s.active.round().totalUnits(),s.betGold,s.level);
  entry.put("total_win",total);entry.put("change_gold",ResultUtil.money(total-ResultUtil.totalBet(s.betGold,s.level)));
  entry.put("round_complete",true);entry.put("round_total_units",s.active.round().totalUnits());
  entry.put("round_feature_win",s.active.round().win());entry.put("round_feature_free",s.active.round().freeFeature());
  entry.put("round_feature_cascade",s.active.round().cascadeFeature());entry.put("round_feature_gold",s.active.round().goldFeature());
  return entry;
 }
 private Map<String,Object>history(SessionState s,Map<String,String>q){synchronized(s){
  String order=q.get("order_id");List<Map<String,Object>>rows=List.copyOf(s.history);
  if(order!=null)rows=rows.stream().filter(r->order.equals(r.get("order_id"))).toList();
  double bet=0,change=0;for(var row:rows){bet+=((Number)row.get("bet_gold")).doubleValue();change+=((Number)row.get("change_gold")).doubleValue();}
  return Map.of("list",rows,"total",rows.size(),"page",1,"page_size",30,"statistics",Map.of("total_bet_gold",ResultUtil.money(bet),"total_change_gold",ResultUtil.money(change)));
 }}
 private Map<String,Object>historyDays(SessionState s){double bet=0,change=0;for(var h:s.history){bet+=((Number)h.getOrDefault("bet_gold",0)).doubleValue();change+=((Number)h.getOrDefault("change_gold",0)).doubleValue();}long day=LocalDate.now(ZoneOffset.UTC).atStartOfDay().toEpochSecond(ZoneOffset.UTC);return Map.of("list",List.of(Map.of("bet_gold",ResultUtil.money(bet),"change_gold",ResultUtil.money(change),"day",day)),"statistics",Map.of("total_bet_gold",ResultUtil.money(bet),"total_change_gold",ResultUtil.money(change)));}
 private Map<String,Object>config(String language){Map<String,Object>server=new LinkedHashMap<>();for(String k:List.of("gos_host","gos_sport","gs_host","gs_host1","gs_port","gs_port1","gs_sport","gs_sport1","gs_push_host","gs_push_port","ps_host","ps_port","snake_gs_host","snake_gs_port","snake_gs_sport","snake_gs_url"))server.put(k,"");server.put("gos_port","8976");server.put("gs_push_sport","28966");server.put("ngs_switch",0);Map<String,Object>out=new LinkedHashMap<>();out.put("game_address",Map.of("ship_address_config",Map.of()));out.put("game_info",Map.of("bet_gold",List.of(.02,.1,.2),"buy_free_max_bet",-1,"default_bet_gold",0,"default_level",10,"game_way",List.of(Map.of("max_bet_gold","0.00","min_bet_gold","0.00","way_id",194010000,"win_multi","1.00")),"gid",1940,"least_gold",0,"name","Magic Scroll","status","1"));out.put("game_server",server);out.put("initial_config",Map.of("bd_bet_count",2,"current_sys_time",Instant.now().getEpochSecond(),"is_debug",false,"is_stopgs",0,"user_on_hook_time",600,"version",1745909504));out.put("language",language);out.put("r",1);out.put("zone",0);out.put("rulesHash",GameRuleCore.RULES_HASH);return out;}
 // The initial screen is not a paid round and must not depend on a populated wager pool.
 static GameRuleCore.Delivery createIdleBoard(){
  GameRuleCore rules=new GameRuleCore();
  var round=new RoundFactory(rules).generate(RoundFactory.Requested.LOSS);
  rules.validate(round);
  if(round.win()||round.freeFeature()||round.totalUnits()!=0)throw new IllegalStateException("invalid idle board");
  return round.deliveries().get(0);
 }
 private Map<String,Object>initRoom(SessionState s){synchronized(s){
  Map<String,Object>data=s.lastData==null?projection.idle(s,idleBoard):new LinkedHashMap<>(s.lastData);
  data.put("end_gold",s.balance);data.put("prop_odds",propOdds());data.put("type_multiple",List.of(List.of(1,2,3,5),List.of(2,4,6,10)));
  return data;
 }}
 private List<Object>propOdds(){int[][]pay={{2,5,10},{2,5,10},{4,10,20},{4,10,20},{6,15,40},{8,20,60},{10,40,80},{15,60,100}};List<Object>out=new ArrayList<>();for(int i=0;i<pay.length;i++)out.add(Map.of("prop_id",i+1,"odds",List.of(Map.of("num",3,"odds",pay[i][0]),Map.of("num",4,"odds",pay[i][1]),Map.of("num",5,"odds",pay[i][2]))));return out;}
 private SessionState session(Map<String,String>q){return sessions.computeIfAbsent(q.getOrDefault("token","demo"),k->new SessionState());}
 private Map<String,Object>ok(Object data){return Map.of("code",0,"data",data,"msg","success","time",String.valueOf(Instant.now().getEpochSecond()));}
 private void staticFile(HttpExchange x,String raw)throws IOException{String path=raw;if(path.equals("/")){String host=x.getRequestHeaders().getFirst("Host");x.getResponseHeaders().set("Location","/v2/1940/index.html?ai=local&btt=1&gid=1940&l=pt&language=pt-br&sip="+host+"&token=demo");x.sendResponseHeaders(302,-1);return;}if(path.startsWith("/v2/1940/"))path=path.substring("/v2/1940".length());else if(path.equals("/v2/reportv2.js"))path="/reportv2.js";Path f=publish.resolve(path.substring(1)).normalize();if(!f.startsWith(publish)||!Files.isRegularFile(f)){send(x,404,Map.of("code",404,"msg","STATIC_NOT_FOUND","path",raw));return;}byte[]body=Files.readAllBytes(f);x.getResponseHeaders().set("Content-Type",content(f));x.sendResponseHeaders(200,body.length);x.getResponseBody().write(body);}
 private String content(Path p){String s=p.toString().toLowerCase(Locale.ROOT);if(s.endsWith(".html"))return"text/html; charset=utf-8";if(s.endsWith(".js"))return"application/javascript; charset=utf-8";if(s.endsWith(".json"))return"application/json";if(s.endsWith(".png"))return"image/png";if(s.endsWith(".jpg"))return"image/jpeg";if(s.endsWith(".mp3"))return"audio/mpeg";if(s.endsWith(".ttf"))return"font/ttf";return"application/octet-stream";}
 private Map<String,String>form(HttpExchange x)throws IOException{String raw=new String(x.getRequestBody().readAllBytes(),StandardCharsets.UTF_8);Map<String,String>out=new LinkedHashMap<>();String ct=Objects.toString(x.getRequestHeaders().getFirst("Content-Type"),"");try{if(ct.contains("json")&&!raw.isBlank()){JsonNode n=json.readTree(raw);n.fields().forEachRemaining(e->out.put(e.getKey(),e.getValue().asText()));}else for(String part:raw.split("&")){if(part.isBlank())continue;String[]kv=part.split("=",2);out.put(URLDecoder.decode(kv[0],StandardCharsets.UTF_8),URLDecoder.decode(kv.length>1?kv[1]:"",StandardCharsets.UTF_8));}}catch(Exception ignored){}String query=x.getRequestURI().getRawQuery();if(query!=null)for(String part:query.split("&")){String[]kv=part.split("=",2);out.putIfAbsent(URLDecoder.decode(kv[0],StandardCharsets.UTF_8),URLDecoder.decode(kv.length>1?kv[1]:"",StandardCharsets.UTF_8));}return out;}
 private double number(Map<String,String>q,String key,double fallback){try{return Double.parseDouble(q.getOrDefault(key,String.valueOf(fallback)));}catch(Exception e){throw new IllegalArgumentException("invalid numeric field "+key);}}
 private void send(HttpExchange x,int status,Object value)throws IOException{byte[]body=json.writeValueAsBytes(value);x.getResponseHeaders().set("Content-Type","application/json; charset=utf-8");x.getResponseHeaders().set("Cache-Control","no-store");x.sendResponseHeaders(status,body.length);x.getResponseBody().write(body);}
 private void cors(HttpExchange x){x.getResponseHeaders().set("Access-Control-Allow-Origin","*");x.getResponseHeaders().set("Access-Control-Allow-Headers","Content-Type");}
 private static Properties load(String[]args)throws IOException{String file="controller.properties";Properties over=new Properties();boolean explicit=false;for(int i=0;i<args.length;i++){String a=args[i];if("--config".equals(a)&&i+1<args.length){file=args[++i];explicit=true;}else if(a.startsWith("--config=")){file=a.substring(9);explicit=true;}else if(a.equals("--publish")&&i+1<args.length)over.setProperty("publish.directory",Path.of(args[++i]).toAbsolutePath().normalize().toString());else if((a.equals("--port")||a.equals("--server.port"))&&i+1<args.length)over.setProperty("server.port",args[++i]);else if(a.matches("\\d{5}"))over.setProperty("server.port",a);else if(!a.startsWith("--")&&!explicit){file=a;explicit=true;}else if(a.startsWith("--")&&a.contains("=")){String[]kv=a.substring(2).split("=",2);over.setProperty(kv[0],kv[1]);}else throw new IllegalArgumentException("unsupported argument "+a);}if(!Files.isRegularFile(Path.of(file))){if(Files.isRegularFile(Path.of("dist",file)))file=Path.of("dist",file).toString();else{try{Path loc=Path.of(ControllerMain.class.getProtectionDomain().getCodeSource().getLocation().toURI());Path dir=Files.isDirectory(loc)?loc:loc.getParent();if(dir!=null){Path nearby=dir.resolve(Path.of(file).getFileName().toString());if(Files.isRegularFile(nearby))file=nearby.toString();}}catch(Exception ignored){}}}Path config=Path.of(file).toAbsolutePath().normalize();Properties p=new Properties();try(Reader r=Files.newBufferedReader(config,StandardCharsets.UTF_8)){p.load(r);}p.putAll(over);String publish=p.getProperty("publish.directory");if(publish!=null&&!Path.of(publish).isAbsolute())p.setProperty("publish.directory",config.getParent().resolve(publish).normalize().toString());String port=System.getenv("PORT");if(port!=null&&!port.isBlank()&&!over.containsKey("server.port"))p.setProperty("server.port",port);return p;}
}
