package com.cpgame.beachfun.api;
import com.cpgame.beachfun.core.*;import java.util.*;

final class ProtocolProjection{
 private final GameRuleCore rules=new GameRuleCore();
 Map<String,Object> project(SessionState s,RedisRoundRepository.Claimed claimed,int index,double bet,int level){var round=claimed.round();var d=round.deliveries().get(index);boolean paid=index==0;double totalBet=ResultUtil.totalBet(bet,level),deliveryWin=0;for(var c:d.cascades())deliveryWin+=ResultUtil.moneyFromUnits(rules.payoutUnits(c.wins()),bet,level);deliveryWin=ResultUtil.money(deliveryWin);double start=s.balance;if(paid)s.balance=ResultUtil.money(s.balance-totalBet);s.balance=ResultUtil.money(s.balance+deliveryWin);double change=ResultUtil.money(deliveryWin-(paid?totalBet:0));if(d.free()){s.priorFreeWin=s.freeWin;s.freeWin=ResultUtil.money(s.freeWin+deliveryWin);}int totalTimes=round.deliveries().stream().limit(index+1L).mapToInt(GameRuleCore.Delivery::awardedFreeSpins).sum();
  Map<String,Object>frees=new LinkedHashMap<>();frees.put("bet",round.freeFeature()?bet:0);frees.put("bet_amount",round.freeFeature()?totalBet:0);frees.put("fw",0);frees.put("last_round_id_win",d.free()?s.priorFreeWin:0);frees.put("level",round.freeFeature()?level:0);frees.put("surplus_times",d.remainingFreeSpins());frees.put("total_times",totalTimes);frees.put("total_win_amount",s.freeWin);
  Map<String,Object>data=new LinkedHashMap<>();data.put("bet",bet);data.put("bet_gold",totalBet);data.put("big",deliveryWin>=totalBet*20?1:0);data.put("big_win",deliveryWin>=totalBet*20);data.put("change_gold",change);data.put("end_gold",s.balance);data.put("frees",frees);data.put("gid",1940);data.put("is_gold_arr",goldArray(d.cascades().get(0)));data.put("level",level);data.put("new_free",Map.of("new_times",d.awardedFreeSpins(),"nums",rules.scatterCount(d.cascades().get(d.cascades().size()-1).board()),"prop",9));data.put("odds",totalBet==0?0:ResultUtil.money(deliveryWin/totalBet));data.put("oid",s.roundId+index);data.put("props",props(d,bet,level));data.put("small_game_type",round.freeFeature()?2:0);data.put("start_gold",start);data.put("total_win",deliveryWin);data.put("type",paid?1:2);data.put("round_fact_id",round.factId());data.put("round_integer_multiplier",claimed.integerMultiplier());return data;
 }
 List<Object>props(GameRuleCore.Delivery d,double bet,int level){List<int[]>ids=rules.cellIds(d);List<Object>out=new ArrayList<>();for(int ci=0;ci<d.cascades().size();ci++){var c=d.cascades().get(ci);Set<Integer>winning=new HashSet<>();for(var w:c.wins())winning.addAll(w.positions());List<Object>columns=new ArrayList<>();int[]board=c.board();boolean[]gold=c.gold();for(int reel=0;reel<GameRuleCore.REELS;reel++){List<Object>col=new ArrayList<>();for(int row=0;row<GameRuleCore.ROWS;row++){int p=reel*GameRuleCore.ROWS+row;col.add(Map.of("id",ids.get(ci)[p],"is_gold",gold[p]?1:0,"is_win",winning.contains(p)?1:0,"prop",board[p]));}columns.add(col);}List<Object>wins=new ArrayList<>();for(var w:c.wins())wins.add(Map.of("multiple",w.multiplier(),"odd",w.odds(),"prop",w.symbol(),"reel",w.reels()-1,"way",w.ways(),"win_amout",ResultUtil.money(w.odds()*w.ways()*w.multiplier()*bet*level)));out.add(Map.of("props_value",columns,"total_amout",ResultUtil.moneyFromUnits(rules.payoutUnits(c.wins()),bet,level),"win_array",wins));}return out;}
 Map<String,Object> idle(SessionState s,GameRuleCore.Delivery d){
  Map<String,Object>data=new LinkedHashMap<>();
  data.put("bet",.02);data.put("bet_gold",4);data.put("big",0);data.put("big_win",false);data.put("change_gold",0);
  data.put("end_gold",s.balance);data.put("start_gold",s.balance);data.put("gid",1940);data.put("level",10);
  data.put("frees",Map.of("bet",0,"bet_amount",0,"fw",0,"last_round_id_win",0,"level",0,"surplus_times",0,"total_times",0,"total_win_amount",0));
  data.put("new_free",Map.of("new_times",0,"nums",rules.scatterCount(d.cascades().get(0).board()),"prop",9));
  data.put("is_gold_arr",goldArray(d.cascades().get(0)));data.put("odds",0);data.put("oid",0);data.put("props",props(d,.02,10));data.put("small_game_type",0);data.put("total_win",0);data.put("type",1);
  return data;
 }
 private List<Object>goldArray(GameRuleCore.Cascade c){List<Object>out=new ArrayList<>();boolean[]g=c.gold();for(int reel=1;reel<=3;reel++){List<String>col=new ArrayList<>();for(int row=0;row<GameRuleCore.ROWS;row++)col.add(g[reel*GameRuleCore.ROWS+row]?"1":"0");out.add(col);}return out;}
}
