server.host=127.0.0.1
publish.root=../../../publish/16-Jungle-Fruit
redis.host=127.0.0.1
redis.port=6399
redis.database=15
redis.connect-timeout-ms=250
redis.read-timeout-ms=250
session.starting-balance=10000.00
