package com.cpgame.g2110.core;
import static org.junit.jupiter.api.Assertions.*;import com.fasterxml.jackson.databind.*;import java.nio.file.*;import java.util.*;import org.junit.jupiter.api.Test;
class GameRuleCoreTest{
 private final GameRuleCore rules=new GameRuleCore();
 @Test void capturedHighWinRecalculatesExactly(){int[]board={1,1,6,1,1,4,1,1,1,1,1,7,7,1,1};assertEquals(6700,rules.payoutUnits(board));assertEquals(12,rules.evaluate(board).size());}
 @Test void allGeneratedKindsValidateAndCodecRoundTrip(){RoundFactory factory=new RoundFactory(rules,new Random(2110));MinimalRoundFactCodec codec=new MinimalRoundFactCodec();ResultUtil util=new ResultUtil(rules);for(var kind:GameRuleCore.RoundKind.values())for(int i=0;i<50;i++){var r=factory.generate(kind);rules.validate(r);String encoded=codec.encode(r);assertTrue(encoded.chars().allMatch(c->c>=32&&c<=126));var decoded=codec.decode(encoded);assertEquals(encoded,codec.encode(decoded));assertEquals(util.integerMultiplier(r),util.integerMultiplier(decoded));}}
 @Test void firstHundredCapturedResponsesMatchRuleOracle()throws Exception{Path root=Path.of("../../fixtures/2110-Bee-Workshop/spin");ObjectMapper json=new ObjectMapper();int checked=0;try(var paths=Files.walk(root)){for(Path path:(Iterable<Path>)paths.filter(p->p.toString().endsWith(".response.json"))::iterator){JsonNode d=json.readTree(path.toFile()).path("data"),props=d.path("props");int[]board=new int[15];for(int i=0;i<15;i++)board[i]=props.path("prop").get(i).asInt();var wins=rules.evaluate(board);assertEquals(props.path("win_arr").size(),wins.size(),path.toString());long units=0;for(int i=0;i<wins.size();i++){var actual=props.path("win_arr").get(i);var expected=wins.get(i);assertEquals(actual.path("line").asInt(),expected.line());assertEquals(actual.path("num").asInt(),expected.num());assertEquals(actual.path("odd").asInt(),expected.odd());assertEquals(actual.path("wp").asInt(),expected.wp());units+=expected.odd();}assertEquals(props.path("tw").asDouble(),units*.02*10,.00001);if(++checked==100)break;}}assertEquals(100,checked);}
 @Test void tenThousandIndependentRoundsRespectInvariants(){RoundFactory f=new RoundFactory(rules,new Random(21002110));int count=0;for(var kind:GameRuleCore.RoundKind.values())for(int i=0;i<2500;i++){rules.validate(f.generate(kind));count++;}assertEquals(10000,count);}
}
