package com.cpgame.g1910.server;

import com.cpgame.g1910.core.GameRuleCore;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.sun.net.httpserver.HttpExchange;
import com.sun.net.httpserver.HttpServer;
import java.math.BigDecimal;
import java.net.*;
import java.nio.charset.StandardCharsets;
import java.nio.file.*;
import java.security.SecureRandom;
import java.time.Instant;
import java.util.*;
import java.util.concurrent.Executors;

/** Controller v3: original static page + provider-shaped API backed only by Redis complete rounds. */
public final class DemoController {
    private final ObjectMapper json=new ObjectMapper();private final ServerConfig config;private final CacheRepository cache;private final StateStore state=new StateStore();private final SecureRandom random=new SecureRandom();private Active active;private volatile CacheRepository.Pool forced;
    private DemoController(ServerConfig config){this.config=config;this.cache=new CacheRepository(config);}
    public static void main(String[]args)throws Exception{Path conf=null,publish=null;int port=0;String bind="0.0.0.0";for(int i=0;i<args.length;i++){if("--config".equals(args[i]))conf=Path.of(args[++i]);else if("--port".equals(args[i]))port=Integer.parseInt(args[++i]);else if("--publish".equals(args[i]))publish=Path.of(args[++i]);else if("--bind".equals(args[i]))bind=args[++i];}if(conf==null)throw new IllegalArgumentException("--config required");if(port==0)port=Integer.parseInt(System.getenv().getOrDefault("PORT","51910"));var app=new DemoController(ServerConfig.load(conf,publish));try(var redis=app.config.openRedis()){redis.ping();}HttpServer server=HttpServer.create(new InetSocketAddress(bind,port),0);server.createContext("/",app::handle);server.setExecutor(Executors.newCachedThreadPool());server.start();System.out.printf("READY http://127.0.0.1:%d/ rulesHash=%s controller=v3 redis=db15%n",port,GameRuleCore.RULES_HASH);}
    private void handle(HttpExchange exchange){try{String path=exchange.getRequestURI().getPath();if("OPTIONS".equals(exchange.getRequestMethod())){cors(exchange);exchange.sendResponseHeaders(204,-1);return;}if(path.equals("/")){String host="127.0.0.1:"+exchange.getLocalAddress().getPort();redirect(exchange,"/fixed/?gid=1910&token=local-1910&language=pt-br&currency=BRL&ai=local&sip="+URLEncoder.encode(host,StandardCharsets.UTF_8));return;}if(path.equals("/favicon.ico")){cors(exchange);exchange.sendResponseHeaders(204,-1);return;}if(path.equals("/health")||path.equals("/api/health")){sendJson(exchange,200,Map.of("status","UP","gameId",1910,"controllerContractVersion",3,"rulesHash",GameRuleCore.RULES_HASH,"redisDatabase",15,"source","redis-complete-round-facts"));return;}if(path.equals("/__qa/force")){forced=pool(params(exchange).getOrDefault("mode","loss"));sendJson(exchange,200,envelope(Map.of("next",forced.name())));return;}if(path.endsWith("/config/initialData")){sendJson(exchange,200,envelope(configData(params(exchange))));return;}if(path.endsWith("/account/getUserInfo")){sendJson(exchange,200,envelope(userData()));return;}if(path.endsWith("/activity/getActivity")){sendJson(exchange,200,envelope(Map.of("free",Map.of("act_list",List.of(),"invite_end_time",0))));return;}if(path.endsWith("/single_game.Game/initRoom")){sendJson(exchange,200,envelope(ProviderPresenter.init(state.balance())));return;}if(path.endsWith("/single_game.Game/gameResult")){sendJson(exchange,200,envelope(spin(params(exchange))));return;}if(path.endsWith("/single_game.game/miniGames")){sendJson(exchange,200,envelope(select(params(exchange))));return;}if(path.endsWith("/config/setGameConfig")){sendJson(exchange,200,envelope(Map.of()));return;}if(path.endsWith("/goldgame/single_game_user_gold_history")){sendJson(exchange,200,envelope(historyDays()));return;}if(path.endsWith("/goldgame/single_game_user_history")){sendJson(exchange,200,envelope(history(params(exchange))));return;}if(path.equals("/api/history")){sendJson(exchange,200,state.history());return;}serveStatic(exchange,path);}catch(Exception error){try{sendJson(exchange,503,Map.of("code",503,"data",Map.of(),"msg",String.valueOf(error.getMessage()),"time",Instant.now().getEpochSecond()));}catch(Exception ignored){}}finally{exchange.close();}}
    private synchronized Map<String,Object>spin(Map<String,String>params){
        if(active!=null){if(!active.timeSelected||!active.multiplierSelected)throw new IllegalStateException("free selectors must complete before continuation");Map<String,Object>response=ProviderPresenter.free(active.round,active.freeIndex,active.bet,active.level,active.start,active.oid,active.results);active.freeIndex++;if(active.freeIndex>=active.round.freeSteps().size())active=null;return response;}
        BigDecimal bet=new BigDecimal(params.getOrDefault("bet_gold","0.02"));int level=Integer.parseInt(params.getOrDefault("level","1"));String requested=params.get("playthrough_kind");CacheRepository.Pool pool=requested==null?forced:pool(requested);forced=null;if(pool==null){double value=random.nextDouble();pool=value<config.freeProbability()?CacheRepository.Pool.FREE:value<config.freeProbability()+config.smallProbability()?CacheRepository.Pool.SMALL:value<config.freeProbability()+config.smallProbability()+config.lossProbability()?CacheRepository.Pool.LOSS:CacheRepository.Pool.WIN;}
        var round=cache.take(pool);BigDecimal start=state.balance(),cost=GameRuleCore.paidBet(bet,level),award=GameRuleCore.award(bet,level,GameRuleCore.evaluate(round).totalUnits());String oid="1910"+System.currentTimeMillis();Map<String,Object>paid=ProviderPresenter.paid(round,bet,level,start,oid);List<Map<String,Object>>responses=new ArrayList<>();responses.add(paid);Map<String,Object>results=defaultResults(round);
        if(round.mode()==GameRuleCore.Mode.FREE_REWARD)for(int i=0;i<round.freeSteps().size();i++)responses.add(ProviderPresenter.free(round,i,bet,level,start,oid,results));
        state.settle(cost,award,historyEntry(paid,responses,oid));if(round.mode()==GameRuleCore.Mode.FREE_REWARD)active=new Active(round,bet,level,start,oid,results);return paid;
    }
    private synchronized Map<String,Object>select(Map<String,String>params){if(active==null)throw new IllegalStateException("no active free-reward round");int index=Math.max(0,Math.min(2,Integer.parseInt(params.getOrDefault("index","0"))));boolean time=Integer.parseInt(params.getOrDefault("time_type","0"))!=0,multiplier=Integer.parseInt(params.getOrDefault("mul_type","0"))!=0;if(!time&&!multiplier)throw new IllegalArgumentException("selector type missing");if(time){active.timeSelected=true;active.timeSelectionIndex=index;}if(multiplier){active.multiplierSelected=true;active.multiplierSelectionIndex=index;}Map<String,Object>response=ProviderPresenter.selector(active.round,active.timeSelected,active.multiplierSelected,active.timeSelectionIndex,active.multiplierSelectionIndex,active.oid);active.results=(Map<String,Object>)response.get("results");return response;}
    private Map<String,Object>defaultResults(GameRuleCore.CompleteRound round){if(round.mode()!=GameRuleCore.Mode.FREE_REWARD)return Map.of();int[]times=GameRuleCore.scatterCount(round.paid().symbols())==4?new int[]{round.freeTimes(),12,16}:new int[]{round.freeTimes(),8,12};int[]multipliers={round.freeMultiplier(),2,5};return Map.of("time",ProviderPresenter.selection(0,times,round.freeTimes()),"multiple",ProviderPresenter.selection(0,multipliers,round.freeMultiplier()));}
    private Map<String,Object>historyEntry(Map<String,Object>paid,List<Map<String,Object>>responses,String oid){Map<String,Object>entry=new LinkedHashMap<>(paid);BigDecimal total=BigDecimal.ZERO;List<Map<String,Object>>steps=new ArrayList<>();for(var response:responses){total=total.add(new BigDecimal(String.valueOf(response.get("total_win"))));Map<String,Object>step=new LinkedHashMap<>(response);if(!step.containsKey("result")&&step.containsKey("props"))step.put("result",step.get("props"));step.put("bet",false);step.putIfAbsent("extend",Map.of("act_bet_gold",0,"act_id","0","act_type",0));steps.add(step);}BigDecimal betGold=new BigDecimal(String.valueOf(paid.get("bet_gold"))),start=new BigDecimal(String.valueOf(paid.get("start_gold")));entry.put("total_win",total);entry.put("change_gold",total.subtract(betGold));entry.put("end_gold",start.subtract(betGold).add(total));entry.put("day",Instant.now().getEpochSecond()/86400*86400);entry.put("time",Instant.now().getEpochSecond());entry.put("order_id",oid+"-1910");entry.put("extend",Map.of("act_bet_gold",0,"act_id","0","act_type",0));entry.put("result",paid.get("props"));entry.put("results",steps);return entry;}
    private Map<String,Object>history(Map<String,String>params){List<Map<String,Object>>all=state.history();int size=Math.max(1,Integer.parseInt(params.getOrDefault("page_size","30"))),page=Math.max(1,Integer.parseInt(params.getOrDefault("page","1"))),from=Math.min(all.size(),(page-1)*size),to=Math.min(all.size(),from+size);return Map.of("list",all.subList(from,to),"statistics",historyTotals(all));}
    private Map<String,Object>historyDays(){
        long today=Instant.now().getEpochSecond()/86400*86400;
        List<Map<String,Object>>days=new ArrayList<>();
        BigDecimal totalBet=BigDecimal.ZERO,totalChange=BigDecimal.ZERO;
        for(int offset=0;offset<7;offset++){
            long day=today-offset*86400L;
            BigDecimal bet=BigDecimal.ZERO,change=BigDecimal.ZERO;
            for(var row:state.history()){
                if(((Number)row.get("day")).longValue()==day){
                    bet=bet.add(new BigDecimal(String.valueOf(row.get("bet_gold"))));
                    change=change.add(new BigDecimal(String.valueOf(row.get("change_gold"))));
                }
            }
            days.add(Map.of("bet_gold",bet,"change_gold",change,"day",day));
            totalBet=totalBet.add(bet);totalChange=totalChange.add(change);
        }
        return Map.of("list",days,"statistics",Map.of("total_bet_gold",totalBet,"total_change_gold",totalChange));
    }
    private Map<String,Object>historyTotals(List<Map<String,Object>>all){return Map.of("total_bet_gold",historyBet(),"total_change_gold",historyChange());}private BigDecimal historyBet(){BigDecimal value=BigDecimal.ZERO;for(var row:state.history())value=value.add(new BigDecimal(String.valueOf(row.get("bet_gold"))));return value;}private BigDecimal historyChange(){BigDecimal value=BigDecimal.ZERO;for(var row:state.history())value=value.add(new BigDecimal(String.valueOf(row.get("change_gold"))));return value;}
    private Map<String,Object>configData(Map<String,String>params){Map<String,Object>game=new LinkedHashMap<>();game.put("bet_gold",List.of(0.5,1,2.5,5,10));game.put("default_bet_gold",0);game.put("default_level",1);game.put("gid",1910);game.put("name","Churrasco");game.put("status",1);game.put("buy_free_max_bet",-1);game.put("game_way",List.of(Map.of("way_id",191010000)));Map<String,Object>server=new LinkedHashMap<>();server.put("ngs_switch",0);server.put("ps_host","");server.put("ps_port",0);server.put("gs_host1","127.0.0.1");server.put("gs_port1",51910);server.put("gs_sport1",0);server.put("gs_push_host","127.0.0.1");server.put("gs_push_port",51910);server.put("gs_push_sport",0);server.put("gos_host","127.0.0.1");server.put("gos_port",51910);server.put("gos_sport",0);return Map.of("game_info",game,"game_server",server,"initial_config",Map.of("current_sys_time",Instant.now().getEpochSecond(),"is_debug",false,"is_stopgs",0,"version",40),"language",params.getOrDefault("language","pt-br"),"r",1,"zone",0,"display_style",Map.of());}
    private Map<String,Object>userData(){return Map.of("token","local-1910","gold",state.balance(),"currency_symbol","R$","currency","BRL","gid",1910,"user_config",Map.of("game_config",Map.of("open_sound",0,"open_music",0)));}
    private static CacheRepository.Pool pool(String value){return switch(value.toLowerCase()){case"win","ordinary_win"->CacheRepository.Pool.WIN;case"small","small_game_1"->CacheRepository.Pool.SMALL;case"free","free_reward","scatter_free_spins"->CacheRepository.Pool.FREE;default->CacheRepository.Pool.LOSS;};}
    private static Map<String,Object>envelope(Object data){return Map.of("code",0,"data",data,"msg","success","time",Instant.now().getEpochSecond());}
    private Map<String,String>params(HttpExchange exchange)throws Exception{String raw=exchange.getRequestURI().getRawQuery();if("POST".equalsIgnoreCase(exchange.getRequestMethod()))raw=(raw==null?"":raw+"&")+new String(exchange.getRequestBody().readAllBytes(),StandardCharsets.UTF_8);Map<String,String>out=new LinkedHashMap<>();if(raw!=null)for(String pair:raw.split("&")){int at=pair.indexOf('=');if(at>=0)out.put(URLDecoder.decode(pair.substring(0,at),StandardCharsets.UTF_8),URLDecoder.decode(pair.substring(at+1),StandardCharsets.UTF_8));}return out;}
    private void serveStatic(HttpExchange exchange,String raw)throws Exception{String relative=raw.startsWith("/fixed/")?raw.substring(7):raw.substring(1);if(relative.isBlank()||relative.endsWith("/"))relative+="index.html";Path file=config.publishDirectory().resolve(relative).normalize();if(!file.startsWith(config.publishDirectory())||!Files.isRegularFile(file)){send(exchange,404,"text/plain; charset=utf-8",("not found: "+raw).getBytes(StandardCharsets.UTF_8));return;}send(exchange,200,mime(file),Files.readAllBytes(file));}
    private static String mime(Path path){String name=path.getFileName().toString().toLowerCase();if(name.endsWith(".html"))return"text/html; charset=utf-8";if(name.endsWith(".js"))return"application/javascript";if(name.endsWith(".json"))return"application/json";if(name.endsWith(".css"))return"text/css";if(name.endsWith(".png"))return"image/png";if(name.endsWith(".jpg"))return"image/jpeg";if(name.endsWith(".mp3"))return"audio/mpeg";if(name.endsWith(".ttf"))return"font/ttf";return"application/octet-stream";}
    private void redirect(HttpExchange exchange,String target)throws Exception{exchange.getResponseHeaders().set("Location",target);exchange.sendResponseHeaders(302,-1);}private void sendJson(HttpExchange exchange,int code,Object body)throws Exception{send(exchange,code,"application/json; charset=utf-8",json.writeValueAsBytes(body));}private void send(HttpExchange exchange,int code,String type,byte[]body)throws Exception{cors(exchange);exchange.getResponseHeaders().set("Content-Type",type);exchange.getResponseHeaders().set("Cache-Control","no-store");exchange.sendResponseHeaders(code,body.length);exchange.getResponseBody().write(body);}private static void cors(HttpExchange exchange){exchange.getResponseHeaders().set("Access-Control-Allow-Origin","*");exchange.getResponseHeaders().set("Access-Control-Allow-Headers","Content-Type");exchange.getResponseHeaders().set("Access-Control-Allow-Methods","GET,POST,OPTIONS");}
    private static final class Active{final GameRuleCore.CompleteRound round;final BigDecimal bet;final int level;final BigDecimal start;final String oid;int freeIndex;boolean timeSelected;boolean multiplierSelected;int timeSelectionIndex;int multiplierSelectionIndex;Map<String,Object>results;Active(GameRuleCore.CompleteRound round,BigDecimal bet,int level,BigDecimal start,String oid,Map<String,Object>results){this.round=round;this.bet=bet;this.level=level;this.start=start;this.oid=oid;this.results=results;}}
}
