#!/usr/bin/env python3
"""Generate CP multi-vendor rules from ai/source; --check never writes."""
from pathlib import Path
import argparse,json
root=Path(__file__).resolve().parent.parent
source=root/'ai/source'
banner='<!-- GENERATED by ai/sync-ai-rules.py; edit ai/source, then sync. -->\n\n'
def generated(text):
 if text.startswith('---\n'):
  end=text.index('\n---',4)+4
  return text[:end]+'\n\n'+banner+text[end:].lstrip('\n')
 return banner+text
def without_frontmatter(text):
 if not text.startswith('---\n'):return text
 end=text.index('\n---',4)+4
 return text[end:].lstrip('\n')
outputs={}
def put(path,text):outputs[root/path]=generated(text)
for name in ['AGENTS.md','复刻要求.md','抓包要求.md']:put(name,(source/name).read_text())
for path in ['CLAUDE.md','.codex/AGENTS.md','.claude/CLAUDE.md','.grok/AGENTS.md','.github/copilot-instructions.md']:
 put(path,'# CPGame 多模型统一入口\n\n先从工作区根读取 AGENTS.md、复刻要求.md、抓包要求.md，按任务读取 skills/ 下对应 SKILL.md 和当前游戏协议。禁止用历史备份或旧代码放宽根规则。唯一编辑点 ai/source，执行 python3 ai/sync-ai-rules.py 及 --check。\n')
body=(source/'rules/shared-hard.md').read_text()
for path in ['.cursor/rules/cpgame-hard.mdc','.claude/rules/cpgame-hard.md','.codex/rules/cpgame-hard.md','.grok/rules/cpgame-hard.md']:
 put(path,('---\ndescription: CPGame shared rules\nalwaysApply: true\n---\n\n' if path.endswith('.mdc') else '')+body)
for skill in sorted((source/'skills').iterdir()):
 if not skill.is_dir() or not (skill/'SKILL.md').is_file():continue
 for folder in ['skills','.grok/skills','.codex/skills','.claude/skills','.cursor/skills','.github/skills']:
  put(f'{folder}/{skill.name}/SKILL.md',(skill/'SKILL.md').read_text())
games=source/'games'
if games.is_dir():
 for game in sorted(games.iterdir()):
  if not game.is_dir() or not (game/'SKILL.md').is_file():continue
  game_text=(game/'SKILL.md').read_text()
  hard_text=without_frontmatter(game_text)
  game_id=game.name
  for path in [f'protocol/{game_id}/AGENTS.md',f'generator/{game_id}/AGENTS.md',f'server-api/{game_id}/AGENTS.md']:
   put(path,hard_text)
  cursor_header=(f'---\ndescription: {game_id} hard game rules\n'
                 f'globs: protocol/{game_id}/**, generator/{game_id}/**, server-api/{game_id}/**\n'
                 'alwaysApply: false\n---\n\n')
  put(f'.cursor/rules/game-{game_id}.mdc',cursor_header+hard_text)
  for path in [f'.claude/rules/game-{game_id}.md',f'.grok/rules/game-{game_id}.md']:
   put(path,hard_text)
  for folder in ['skills','.grok/skills','.claude/skills','.cursor/skills','.github/skills']:
   put(f'{folder}/{game_id}/SKILL.md',game_text)
args=argparse.ArgumentParser();args.add_argument('--check',action='store_true');check=args.parse_args().check
bad=[];changed=0
for path,text in outputs.items():
 if not path.exists() or path.read_text()!=text:
  if check:bad.append(str(path.relative_to(root)))
  else:path.parent.mkdir(parents=True,exist_ok=True);path.write_text(text);changed+=1
if bad:print('Mismatch: '+', '.join(bad));raise SystemExit(1)
if not check:(root/'ai/targets.json').write_text(json.dumps([str(p.relative_to(root)) for p in outputs],indent=2)+'\n')
print(f'{"check OK" if check else "sync OK"}: {len(outputs)} files; changed={changed}')
