port 6379
bind 192.168.10.3 127.0.0.1
databases 16
timeout 0
tcp-keepalive 0
loglevel notice
logfile ""
save 900000000 1
appendonly no
dir D:/work/hd/cpgame/redis-pack/41-Lucky-Panda
dbfilename demo-db15.rdb
maxmemory 256mb
maxmemory-policy allkeys-lru
