server.address=0.0.0.0
server.port=${CURUPIRA_API_PORT:19500}
server.shutdown=graceful
spring.jackson.deserialization.use-big-decimal-for-floats=true
curupira.initial-balance=${CURUPIRA_INITIAL_BALANCE:1000.00}
curupira.signature.required=${CURUPIRA_SIGNATURE_REQUIRED:false}
curupira.history-limit=${CURUPIRA_HISTORY_LIMIT:500}
curupira.redis.enabled=${CURUPIRA_REDIS_ENABLED:true}
curupira.redis.host=18.234.101.161
curupira.redis.port=8021
curupira.redis.database=0
curupira.redis.username=
curupira.redis.password=pssss@6j&NHIjpB
curupira.redis.ssl=false
curupira.redis.connect-timeout-ms=5000
curupira.redis.socket-timeout-ms=30000
curupira.redis.game-id=8002350
