package com.cpgame.monsterslayer.server;

import com.cpgame.monsterslayer.core.GameRuleCore;import com.fasterxml.jackson.databind.ObjectMapper;import com.sun.net.httpserver.Headers;import com.sun.net.httpserver.HttpExchange;import com.sun.net.httpserver.HttpServer;
import java.io.IOException;import java.math.BigDecimal;import java.net.*;import java.nio.charset.StandardCharsets;import java.nio.file.Files;import java.nio.file.Path;import java.util.LinkedHashMap;import java.util.Locale;import java.util.Map;import java.util.Properties;import java.util.concurrent.Executors;

/** Contract-v3 single-process static and API Controller. */
public final class MonsterSlayerController {
    private static final ObjectMapper JSON=new ObjectMapper();private final Path publishRoot;private final MonsterSlayerService service;
    private MonsterSlayerController(Path publishRoot,MonsterSlayerService service){this.publishRoot=publishRoot;this.service=service;}
    public static void main(String[]args)throws Exception{Map<String,String>opts=options(args);int port=requiredPort(opts);Properties cfg=loadConfig(opts.get("config"));rejectUnsafe(cfg);Path publish=resolvePublish(opts.getOrDefault("publish",cfg.getProperty("publish.directory","")));RedisRoundStore redis=RedisRoundStore.connect(cfg);MonsterSlayerController c=new MonsterSlayerController(publish,new MonsterSlayerService(redis,new BigDecimal(cfg.getProperty("session.initial-balance","10000.00"))));HttpServer server=HttpServer.create(new InetSocketAddress("0.0.0.0",port),0);server.createContext("/",c::handle);server.setExecutor(Executors.newFixedThreadPool(Math.max(4,Runtime.getRuntime().availableProcessors())));Runtime.getRuntime().addShutdownHook(new Thread(()->{server.stop(0);try{redis.close();}catch(IOException ignored){}}));server.start();System.out.printf("CONTROLLER_READY gameId=2300 port=%d pid=%d rulesVersion=%s rulesHash=%s publish=%s redis=%s%n",port,ProcessHandle.current().pid(),GameRuleCore.RULES_VERSION,GameRuleCore.RULES_HASH,publish,redisEndpoint(cfg));}
    private void handle(HttpExchange x)throws IOException{try{if("OPTIONS".equalsIgnoreCase(x.getRequestMethod())){sendEmpty(x,204);return;}String path=x.getRequestURI().getPath();if("GET".equalsIgnoreCase(x.getRequestMethod())||"HEAD".equalsIgnoreCase(x.getRequestMethod())){Map<String,String>q=query(x.getRequestURI().getRawQuery());if(path.equals("/health")||path.equals("/__controller/status")||path.equals("/api/session")){sendJson(x,200,service.status(q));return;}if(path.equals("/api/balance")){sendJson(x,200,service.balance(q));return;}if(path.equals("/cp/activity/getActivity")||path.equals("/activity/getActivity")){sendJson(x,200,service.activity());return;}serveStatic(x);return;}if(!"POST".equalsIgnoreCase(x.getRequestMethod())){sendJson(x,405,MonsterSlayerService.error(405,"POST required"));return;}Map<String,String>f=form(x);switch(path){case"/cp/config/initialData","/config/initialData"->sendJson(x,200,service.config(f,hostPort(x)));case"/cp/account/getUserInfo","/account/getUserInfo"->sendJson(x,200,service.user(f));case"/cp/activity/getActivity","/activity/getActivity"->sendJson(x,200,service.activity());case"/cp/single_game.Game/initRoom","/single_game.Game/initRoom"->sendJson(x,200,service.init(f));case"/cp/single_game.Game/gameResult","/single_game.Game/gameResult"->sendJson(x,200,service.spin(f));case"/cp/goldgame/single_game_user_gold_history","/goldgame/single_game_user_gold_history"->sendJson(x,200,service.historySummary(f));case"/cp/goldgame/single_game_user_history","/goldgame/single_game_user_history"->sendJson(x,200,service.historyDetail(f));case"/api/balance"->sendJson(x,200,service.balance(f));case"/api/session"->sendJson(x,200,service.status(f));case"/api/report/timing","/cp/report/timing"->sendEmpty(x,204);default->sendJson(x,404,MonsterSlayerService.error(404,"unknown endpoint: "+path));}}catch(IllegalStateException|IOException e){sendJson(x,200,MonsterSlayerService.error(503,e.getMessage()));}catch(IllegalArgumentException e){sendJson(x,200,MonsterSlayerService.error(400,e.getMessage()));}catch(Exception e){e.printStackTrace();sendJson(x,200,MonsterSlayerService.error(500,"controller failure"));}finally{x.close();}}
    private void serveStatic(HttpExchange x)throws IOException{URI u=x.getRequestURI();if(u.getPath().equals("/")&&needsRewrite(u.getRawQuery(),x)){x.getResponseHeaders().set("Location","/?"+rewritten(u.getRawQuery(),x));sendEmpty(x,302);return;}String raw=u.getPath().isEmpty()||u.getPath().equals("/")?"/index.html":u.getPath();Path file=publishRoot.resolve(raw.substring(1)).normalize();if(!file.startsWith(publishRoot)||!Files.isRegularFile(file)){sendJson(x,404,MonsterSlayerService.error(404,"static file not found"));return;}byte[]body=Files.readAllBytes(file);cors(x);x.getResponseHeaders().set("Content-Type",mime(file));x.getResponseHeaders().set("Cache-Control","no-store");if("HEAD".equalsIgnoreCase(x.getRequestMethod())){x.sendResponseHeaders(200,-1);return;}send(x,200,body);}
    private static boolean needsRewrite(String raw,HttpExchange x){Map<String,String>q=query(raw);String hp=hostPort(x);return!"2300".equals(q.get("gid"))||!hp.equalsIgnoreCase(q.getOrDefault("sip",""))||!q.containsKey("t")||!q.containsKey("token")||!q.containsKey("language");}
    private static String rewritten(String raw,HttpExchange x){Map<String,String>q=new LinkedHashMap<>(query(raw));q.putIfAbsent("ai","luck_single_10229");q.putIfAbsent("btt","1");q.put("gid","2300");q.putIfAbsent("l","en");q.putIfAbsent("language","en-us");q.put("sip",hostPort(x));q.putIfAbsent("t","local-session");q.putIfAbsent("token",q.get("t"));return q.entrySet().stream().map(e->encode(e.getKey())+"="+encode(e.getValue())).reduce((a,b)->a+"&"+b).orElse("gid=2300");}
    private static Map<String,String>form(HttpExchange x)throws IOException{Map<String,String>r=new LinkedHashMap<>(query(new String(x.getRequestBody().readAllBytes(),StandardCharsets.UTF_8)));r.putAll(query(x.getRequestURI().getRawQuery()));return r;}
    private static Map<String,String>query(String raw){Map<String,String>r=new LinkedHashMap<>();if(raw==null||raw.isBlank())return r;for(String p:raw.split("&")){String[]v=p.split("=",2);r.put(decode(v[0]),v.length>1?decode(v[1]):"");}return r;}
    private static void sendJson(HttpExchange x,int status,Object v)throws IOException{cors(x);x.getResponseHeaders().set("Content-Type","application/json; charset=UTF-8");x.getResponseHeaders().set("Cache-Control","no-store");send(x,status,JSON.writeValueAsBytes(v));}
    private static void sendEmpty(HttpExchange x,int status)throws IOException{cors(x);send(x,status,new byte[0]);}
    private static void send(HttpExchange x,int status,byte[]body)throws IOException{x.sendResponseHeaders(status,body.length);if(body.length>0)x.getResponseBody().write(body);}
    private static void cors(HttpExchange x){Headers h=x.getResponseHeaders();String origin=x.getRequestHeaders().getFirst("Origin");h.set("Access-Control-Allow-Origin",origin!=null&&!origin.isBlank()?origin:"*");h.set("Access-Control-Allow-Headers","Content-Type, Idempotency-Key");h.set("Access-Control-Allow-Methods","GET, POST, OPTIONS, HEAD");}
    private static String mime(Path p){String n=p.getFileName().toString().toLowerCase(Locale.ROOT);if(n.endsWith(".html"))return"text/html; charset=utf-8";if(n.endsWith(".js"))return"application/javascript; charset=utf-8";if(n.endsWith(".json"))return"application/json; charset=utf-8";if(n.endsWith(".css"))return"text/css";if(n.endsWith(".png"))return"image/png";if(n.endsWith(".webp"))return"image/webp";if(n.endsWith(".wasm"))return"application/wasm";if(n.endsWith(".mp3"))return"audio/mpeg";if(n.endsWith(".ttf"))return"font/ttf";return"application/octet-stream";}
    static Map<String,String>options(String[]args){
        Map<String,String>r=new LinkedHashMap<>();
        for(int i=0;i<args.length;i++){
            String a=args[i];
            if(!a.startsWith("--")){if(!r.containsKey("config"))r.put("config",a);continue;}
            String body=a.substring(2);
            int eq=body.indexOf('=');
            if(eq>=0){r.put(body.substring(0,eq),body.substring(eq+1));continue;}
            String v=i+1<args.length&&!args[i+1].startsWith("--")?args[++i]:"true";
            r.put(body,v);
        }
        return r;
    }
    static int requiredPort(Map<String,String>o){String v=first(o.get("port"),o.get("server.port"),System.getProperty("cpgame.demo.port"),System.getenv("CPGAME_DEMO_PORT"),System.getenv("PORT"));if(v==null||v.isBlank())throw new IllegalArgumentException("platform must inject --port in range 50000-59999");int p=Integer.parseInt(v.trim());if(p<50000||p>59999)throw new IllegalArgumentException("port must be 50000-59999");return p;}
    private static String redisEndpoint(Properties p){return p.getProperty("redis.host")+":"+p.getProperty("redis.port")+" db="+p.getProperty("redis.database")+" gameId="+p.getProperty("redis.game-id");}
    private static Properties loadConfig(String value)throws IOException{Properties p=new Properties();p.setProperty("redis.host","18.234.101.161");p.setProperty("redis.port","8021");p.setProperty("redis.database","0");p.setProperty("redis.game-id","8002300");if(value!=null&&!value.isBlank())try(var r=Files.newBufferedReader(Path.of(value).toAbsolutePath(),StandardCharsets.UTF_8)){p.load(r);}return p;}
    private static void rejectUnsafe(Properties p){for(String k:p.stringPropertyNames())if(k.toLowerCase(Locale.ROOT).contains("seed"))throw new IllegalArgumentException("seed properties forbidden");if(p.containsKey("port")||p.containsKey("controller.api-port"))throw new IllegalArgumentException("hard-coded Controller port forbidden");if(!p.getProperty("redis.host").equals("18.234.101.161")||!p.getProperty("redis.port").equals("8021")||Integer.parseInt(p.getProperty("redis.database")) < 0)throw new IllegalArgumentException("Invalid Redis endpoint: "+redisEndpoint(p));}
    private static Path resolvePublish(String value)throws Exception {
        Path location=Path.of(MonsterSlayerController.class.getProtectionDomain().getCodeSource().getLocation().toURI()).toAbsolutePath();
        Path jarDirectory=Files.isRegularFile(location)?location.getParent():location;
        Path selected;
        if(value!=null&&!value.isBlank()) {
            Path requested=Path.of(value);
            selected=(requested.isAbsolute()?requested:jarDirectory.resolve(requested)).normalize();
        } else {
            selected=jarDirectory.resolve("../../../publish/2300-Monster-Slayer").normalize();
        }
        if(!Files.isRegularFile(selected.resolve("index.html")))throw new IllegalArgumentException("publish/index.html not found: "+selected);
        return selected;
    }
    private static String hostPort(HttpExchange x){String h=x.getRequestHeaders().getFirst("Host");return h==null||h.isBlank()?x.getLocalAddress().getHostString()+":"+x.getLocalAddress().getPort():h;}
    private static String encode(String v){return URLEncoder.encode(v,StandardCharsets.UTF_8).replace("+","%20");}private static String decode(String v){return URLDecoder.decode(v,StandardCharsets.UTF_8);}private static String first(String...v){for(String s:v)if(s!=null&&!s.isBlank())return s;return null;}
}
