package com.cpgame.batchd.treasurehunt.api;

import com.fasterxml.jackson.core.type.TypeReference;import com.fasterxml.jackson.databind.ObjectMapper;import java.math.BigDecimal;import java.nio.file.Files;import java.nio.file.Path;import java.nio.file.StandardCopyOption;import java.time.Instant;import java.time.ZoneOffset;import java.time.format.DateTimeFormatter;import java.util.ArrayList;import java.util.LinkedHashMap;import java.util.List;import java.util.Map;

final class StateStore{private final Path file;private final ObjectMapper json;private BigDecimal balance;private long nextOrder;private final List<Map<String,Object>>history;
    StateStore(Path file,ObjectMapper json)throws Exception{this.file=file;this.json=json;if(Files.isRegularFile(file)){Map<String,Object>d=json.readValue(file.toFile(),new TypeReference<>(){});balance=new BigDecimal(String.valueOf(d.getOrDefault("balance","100000.00")));nextOrder=((Number)d.getOrDefault("nextOrder",1)).longValue();history=new ArrayList<>((List<Map<String,Object>>)d.getOrDefault("history",List.of()));for(Map<String,Object>entry:history){Map<String,Object>extend=new LinkedHashMap<>();if(entry.get("extend")instanceof Map<?,?>old)for(var item:old.entrySet())extend.put(String.valueOf(item.getKey()),item.getValue());extend.putIfAbsent("act_bet_gold",0);extend.putIfAbsent("act_id","0");extend.putIfAbsent("act_type",0);entry.put("extend",extend);}}else{balance=new BigDecimal("100000.00");nextOrder=1;history=new ArrayList<>();save();}}
    synchronized Snapshot snapshot(){return new Snapshot(balance,List.copyOf(history));}
    synchronized Applied apply(BigDecimal betCost,BigDecimal win,Map<String,Object>detail)throws Exception{BigDecimal start=balance;balance=balance.subtract(betCost).add(win);long n=nextOrder++;String oid=String.format("1810-%012d",n);long now=Instant.now().getEpochSecond();Map<String,Object>entry=new LinkedHashMap<>(detail);entry.put("oid",oid);entry.put("order_id",oid+"-1810");entry.put("start_gold",start);entry.put("end_gold",balance);entry.put("change_gold",win.subtract(betCost));entry.put("time",now);entry.put("day",now);history.add(0,entry);if(history.size()>500)history.remove(history.size()-1);save();return new Applied(oid,start,balance,win.subtract(betCost),now,now,entry);}
    private void save()throws Exception{Files.createDirectories(file.getParent());Path tmp=file.resolveSibling(file.getFileName()+".tmp");Map<String,Object>d=Map.of("balance",balance,"nextOrder",nextOrder,"history",history);json.writerWithDefaultPrettyPrinter().writeValue(tmp.toFile(),d);Files.move(tmp,file,StandardCopyOption.REPLACE_EXISTING,StandardCopyOption.ATOMIC_MOVE);}
    record Snapshot(BigDecimal balance,List<Map<String,Object>>history){}record Applied(String oid,BigDecimal start,BigDecimal end,BigDecimal change,long time,long day,Map<String,Object>entry){}
}
